#version 330
out vec4 outColor;

// GENERATED by Tools/build_volumetric_starfield.py from the source's .frag -- do not edit by hand.
// SHADERed build: #version must be the literal first line, and its GLSL mode is
// Shadertoy-compatible (iResolution / iMouse / iTime).
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables, so its preview camera drives the view.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

// Knob values live in the .sprj: GLSL uniforms cannot have initialisers.
uniform float uStvCell;
uniform float uStvDensity;
uniform float uStvView;
uniform float uStvAng;
uniform float uStvBright;
uniform float uStvFalloff;
uniform float uStvSeed;

// ===== PHYSICS ==================================================================
// The lattice, the star model and the contract live in volumetric_starfield.inc.glsl (below).

// ===== SHARED MATHS =============================================================
// volumetric_starfield.inc.glsl — a starfield you can FLY THROUGH.
//
// `Space/Starfield` is a DOME: every star sits on the celestial sphere at radius=cells, so it
// never moves relative to the viewer. That is correct for distant stars (their parallax is
// unmeasurable) but it means flying gives no sense of travel at all.
//
// This layer is a VOLUME: stars sit on a world-anchored lattice around the viewer, so passing
// them produces real parallax and near ones sweep by quickly.
//
// It is deliberately LOCAL -- the march stops at uStvView. Beyond that the dome takes over.
// That split is not just cheap, it is necessary: a star is a point source, so its ANGULAR size
// is constant, which means the cylinder a single pixel sweeps out has radius
// (angular size x distance) and GROWS without limit. Past some range that cylinder is wider
// than a cell, and any one-cell-per-step test starts missing stars that are near the ray but
// in a neighbouring cell. Bounded, that cannot happen, and distant stars are the dome's job
// anyway -- where parallax is genuinely negligible.
//
// Contract (same shape as the nebula layers):
//     vec3 volumetricStarfieldSky(vec3 camPos, vec3 dir, float pxPerDir, float dither, out vec3 transmittance);
// Stars absorb nothing, so transmittance is always 1 -- exactly like the dome.
//
// GPL-3.0 (see LICENSE at the repository root).

#ifndef VOLUMETRIC_STARFIELD_GLSLINC
#define VOLUMETRIC_STARFIELD_GLSLINC

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/noise.glsl — value noise and fbm, built on lib/hash.glsl.
//
// Requires hash13() to be included first.
//
// GPL-3.0 (see LICENSE at the repository root).

// low-frequency value noise (once per pixel is plenty at these frequencies)

#ifndef LIB_NOISE_GLSL
#define LIB_NOISE_GLSL

float vnoise(vec3 p) {
	vec3 i = floor(p), f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float n = 0.0;
	for (int z = 0; z < 2; z++)
	for (int y = 0; y < 2; y++)
	for (int x = 0; x < 2; x++) {
		vec3 o = vec3(float(x), float(y), float(z));
		n += hash13(i + o) * (mix(1.0 - f.x, f.x, o.x)
		                    * mix(1.0 - f.y, f.y, o.y)
		                    * mix(1.0 - f.z, f.z, o.z));
	}
	return n;
}
float fbm3(vec3 p) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 3; i++) { s += a * vnoise(p); t += a; p *= 2.03; a *= 0.5; }
	return s / t;
}


#endif  // LIB_NOISE_GLSL
// lib/raymarch.glsl — helpers for raymarched volumetric layers.
//
// Pure maths with no host assumptions: camera basis, ray/box intersection, phase
// functions, and a texture-free dither. Included (inlined) by Tools/build_*.glsl.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_RAYMARCH_GLSL
#define LIB_RAYMARCH_GLSL

#ifndef PI
#define PI 3.141592653589793
#endif

// Slab-method ray/AABB intersection (DomNomNom). Returns (tNear, tFar) in ray units;
// there is no hit when tNear > tFar.
vec2 intersectAABB(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax) {
	vec3 tMin = (bmin - ro) / rd;
	vec3 tMax = (bmax - ro) / rd;
	vec3 t1 = min(tMin, tMax);
	vec3 t2 = max(tMin, tMax);
	return vec2(max(max(t1.x, t1.y), t1.z), min(min(t2.x, t2.y), t2.z));
}

// Henyey-Greenstein phase function. g in (-1, 1): negative scatters back, positive
// forward. mu is the cosine between the view ray and the light direction.
float hgPhase(float g, float cosTheta) {
	return (1.0 / (4.0 * PI)) * ((1.0 - g * g) / pow(1.0 + g * g - 2.0 * g * cosTheta, 1.5));
}

// Interleaved gradient noise: a cheap per-pixel dither, used to offset the first ray
// step so the marching does not band. No blue-noise texture needed, so it works in
// every host (SHADERed, glslviewer, Godot).
float ign(vec2 fragCoord) {
	return fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
}

// Camera basis: columns are right, up, -forward, so a view-space ray (forward is -Z)
// maps into world space. `fwd` is the direction the camera looks.
mat3 lookAt(vec3 fwd, vec3 up) {
	vec3 zaxis = normalize(fwd);
	vec3 xaxis = normalize(cross(zaxis, up));
	vec3 yaxis = cross(xaxis, zaxis);
	return mat3(xaxis, yaxis, -zaxis);
}


#endif  // LIB_RAYMARCH_GLSL

#define STV_MAX_STEPS 640   // hard cap on the march

// Star colour: hotter (bluer) for the bright ones, cooler for the dim, which is the usual
// cheap approximation of spectral type.
vec3 starTint(float m) {
	return mix(vec3(1.00, 0.82, 0.66), vec3(0.78, 0.86, 1.00), clamp(m, 0.0, 1.0));
}

vec3 volumetricStarfieldSky(vec3 camPos, vec3 dir, float pxPerDir, float dither, out vec3 transmittance) {
	vec3 d = normalize(dir);
	transmittance = vec3(1.0);            // stars do not absorb

	// Step at HALF a cell so the ray cannot stride over a whole cell, and evaluate a cell only
	// when the ray ENTERS it (tracked via `lastCell`). That dedup is what stops a star being
	// counted once per step. A 3D DDA would be exact; this is the cheap version, and at
	// half-cell steps the only cells it can miss are the ones clipped at a corner.
	float dt = max(uStvCell, 1e-4) * 0.5;
	int steps = min(int(uStvView / dt) + 1, STV_MAX_STEPS);

	vec3 col = vec3(0.0);
	vec3 lastCell = vec3(-1e9);            // guaranteed != the first cell

	for (int i = 0; i < STV_MAX_STEPS; i++) {
		if (i >= steps) break;
		float t = (float(i) + dither) * dt;
		vec3 p = camPos + d * t;

		vec3 c = floor(p / uStvCell);
		if (c == lastCell) continue;
		lastCell = c;

		vec3 r = hash33(c + uStvSeed);
		if (r.x > uStvDensity) continue;    // this cell holds no star

		// Keep the star clear of the cell walls (the inner 70%). That keeps its disc out of a
		// neighbouring cell's ray segment, which is what makes the one-cell test safe.
		vec3 P = (c + 0.15 + 0.70 * r.yzx) * uStvCell;

		vec3 rel = P - camPos;
		float along = dot(rel, d);
		if (along <= 0.0) continue;         // behind us

		float dperp = length(rel - along * d);
		float ang = dperp / along;          // angular offset from this pixel's ray

		float mag = r.z;                                             // 0..1: size + luminosity
		float rr = uStvAng * (0.95 + 0.45 * mag);                    // constant ANGULAR radius

		if (ang >= rr) continue;

		// Sub-pixel stars fade rather than being lost or fattened, so the field stays
		// resolution-independent -- the same rule as the dome.
		float radPx = rr / max(pxPerDir, 1e-9);
		float cover = clamp(radPx, 0.0, 1.0);

		// Disc falloff, then inverse-square: flying towards a star makes it brighter.
		float q = 1.0 - ang / rr;
		float flux = q * q * cover * cover / (1.0 + along * along * uStvFalloff);

		col += uStvBright * (0.30 + 0.70 * mag) * flux * starTint(mag);
	}

	return col;
}

#endif  // VOLUMETRIC_STARFIELD_GLSLINC

vec3 aces(vec3 x) {
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

void main() {
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	// Dither the first step per pixel, or flying forward slides the sampling lattice.
	float dither = ign(gl_FragCoord.xy);
	vec3 transmittance;
	vec3 col = volumetricStarfieldSky(uCamPos, dir, pxPerDir, dither, transmittance);

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}
