#version 330
out vec4 outColor;

// GENERATED by Tools/build_scenes.py via Tools/shader_build.py from /home/evert/Software/Projects/Shaders/Space/Scenes/nebula-and-stars.frag -- do not edit by hand.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed, and its
// GLSL mode is Shadertoy-compatible (iResolution / iMouse / iTime).
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables: driven by SHADERed's own preview camera.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

// The knob values live in the .sprj, not here: GLSL uniforms cannot have initialisers,
// which is why SHADERed shows them as variables you can edit (right-click the pass ->
// Variables, then pin them with +).
uniform float uStars;
uniform float uFilScale;
uniform float uFilFreq;
uniform float uFilVoid;
uniform float uFilCore;
uniform float uFilDensity;
uniform float uFilView;
uniform float uFilSteps;
uniform float uFilBright;
uniform float uFilHue;
uniform float uFilSat;
uniform float uFilHueRange;
uniform float uFilHueScale;
uniform vec3 uFilBg;
uniform float uFilOpacity;
uniform float uFilWarp;
uniform float uFilWarpScale;
uniform float uStvCell;
uniform float uStvDensity;
uniform float uStvView;
uniform float uStvAng;
uniform float uStvBright;
uniform float uStvFalloff;
uniform float uStvSeed;

// ===== PHYSICS ==================================================================
// A scene owns no physics of its own: each layer brings its own from its .inc.glsl --
// ridged-clouds supplies the gas, volumetric_starfield the stars. This marker exists
// because the builders split the source on it.

// ===== SHARED MATHS =============================================================
// ridged-clouds.inc.glsl — a raymarched filamentary nebula.
//
// The density field is a RIDGED FILAMENT network: successive rotated sine waves, rectified
// so the field peaks along thin strands instead of forming smooth blobs. That is what a
// supernova remnant or an HII region actually looks like, and it is a different family from
// the gyroid fbm in Space/Nebula/gyroid-clouds.
//
// INSPIRATION, NO CODE TAKEN. The idea of stacking rotated, rectified sine waves for
// filamentary structure comes from the "spiral noise" used on Shadertoy (otaviogood), and
// the superstructure march that popularised it is Duke's / sebastien durand's "Type 2
// Supernova". Those shaders are CC BY-NC-SA, which is incompatible with this repo's GPL-3.0
// (NonCommercial forbids what the GPL grants; ShareAlike conflicts with it). So this is an
// independent implementation of the *technique*: our own rotation construction, our own
// marching, our own lighting and colour, and this repo's layer contract.
//
// GPL-3.0 (see LICENSE at the repository root).

#ifndef RIDGED_CLOUDS_GLSLINC
#define RIDGED_CLOUDS_GLSLINC

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/noise.glsl — value noise and fbm, built on lib/hash.glsl.
//
// Requires hash13() to be included first.
//
// GPL-3.0 (see LICENSE at the repository root).

// low-frequency value noise (once per pixel is plenty at these frequencies)

#ifndef LIB_NOISE_GLSL
#define LIB_NOISE_GLSL

float vnoise(vec3 p) {
	vec3 i = floor(p), f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float n = 0.0;
	for (int z = 0; z < 2; z++)
	for (int y = 0; y < 2; y++)
	for (int x = 0; x < 2; x++) {
		vec3 o = vec3(float(x), float(y), float(z));
		n += hash13(i + o) * (mix(1.0 - f.x, f.x, o.x)
		                    * mix(1.0 - f.y, f.y, o.y)
		                    * mix(1.0 - f.z, f.z, o.z));
	}
	return n;
}
float fbm3(vec3 p) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 3; i++) { s += a * vnoise(p); t += a; p *= 2.03; a *= 0.5; }
	return s / t;
}


#endif  // LIB_NOISE_GLSL
// lib/raymarch.glsl — helpers for raymarched volumetric layers.
//
// Pure maths with no host assumptions: camera basis, ray/box intersection, phase
// functions, and a texture-free dither. Included (inlined) by Tools/build_*.glsl.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_RAYMARCH_GLSL
#define LIB_RAYMARCH_GLSL

#ifndef PI
#define PI 3.141592653589793
#endif

// Slab-method ray/AABB intersection (DomNomNom). Returns (tNear, tFar) in ray units;
// there is no hit when tNear > tFar.
vec2 intersectAABB(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax) {
	vec3 tMin = (bmin - ro) / rd;
	vec3 tMax = (bmax - ro) / rd;
	vec3 t1 = min(tMin, tMax);
	vec3 t2 = max(tMin, tMax);
	return vec2(max(max(t1.x, t1.y), t1.z), min(min(t2.x, t2.y), t2.z));
}

// Henyey-Greenstein phase function. g in (-1, 1): negative scatters back, positive
// forward. mu is the cosine between the view ray and the light direction.
float hgPhase(float g, float cosTheta) {
	return (1.0 / (4.0 * PI)) * ((1.0 - g * g) / pow(1.0 + g * g - 2.0 * g * cosTheta, 1.5));
}

// Interleaved gradient noise: a cheap per-pixel dither, used to offset the first ray
// step so the marching does not band. No blue-noise texture needed, so it works in
// every host (SHADERed, glslviewer, Godot).
float ign(vec2 fragCoord) {
	return fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
}

// Camera basis: columns are right, up, -forward, so a view-space ray (forward is -Z)
// maps into world space. `fwd` is the direction the camera looks.
mat3 lookAt(vec3 fwd, vec3 up) {
	vec3 zaxis = normalize(fwd);
	vec3 xaxis = normalize(cross(zaxis, up));
	vec3 yaxis = cross(xaxis, zaxis);
	return mat3(xaxis, yaxis, -zaxis);
}


#endif  // LIB_RAYMARCH_GLSL


#define FILAMENT_OCTAVES 6    // ridge octaves (cost driver)
#define FIL_MAX_STEPS   192   // hard cap on the march loop

// Extinction colour: what the gas absorbs. Dust-ish, slightly blue.
const vec3 FIL_ABSORB = vec3(0.55, 0.75, 1.00);

// A rotation that mixes all three axes, used to reorient the ridge family each octave.
mat3 filRotate(float a, float b) {
	float ca = cos(a), sa = sin(a), cb = cos(b), sb = sin(b);
	return mat3(vec3(ca, sa, 0.0), vec3(-sa, ca, 0.0), vec3(0.0, 0.0, 1.0))
	     * mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, cb, sb), vec3(0.0, -sb, cb));
}

// Ridged filament field in [0,1].
//
// Each octave measures a wave along two axes. Rectifying with 1 - |...| keeps only the
// ridges and throws the bulk away, so what survives is a network of thin bright strands.
// Rotating the sample between octaves crosses those families, and squaring sharpens them.
float filamentField(vec3 p) {
	mat3 rot = filRotate(1.13, 0.71);
	float acc = 0.0, weight = 0.0, amp = 1.0;
	for (int i = 0; i < FILAMENT_OCTAVES; i++) {
		float r = 1.0 - clamp(abs(sin(p.y) + 0.85 * cos(p.x)), 0.0, 1.0);
		acc += amp * r * r;             // square: sharpen the strand
		weight += amp;
		p = (rot * p) * uFilFreq;       // rise in frequency AND reorient
		amp *= 0.62;
	}
	return clamp(acc / weight * 1.6, 0.0, 1.0);
}

// Hue/val colour, our own (standard) conversion.
vec3 filHSV(vec3 c) {
	vec3 p = abs(fract(c.xxx + vec3(0.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
	return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);
}

// The strand colour. The hue is held INSIDE A PALETTE: every variation is scaled into
// uFilHueRange around uFilHue, so the strands are a family of related hues rather than a
// trip around the whole wheel. uFilHueRange 1.0 restores the old cycle-everything look.
//
// Where the hue varies from is the important part. It comes from the DENSITY FIELD and from a
// noise sampled in WARPED space (q), so the colour follows the gas. It deliberately does NOT
// use the light lattice: that is a grid, and the creases of a grid are STRAIGHT -- warping
// them by the field's displacement is useless, because that displaces by only ~0.4 world
// units against a 5-unit cell (~8%), which leaves the creases straight. At a tight hue range
// nobody notices; widen the range and you get straight colour bands running through an
// otherwise curly cloud. So colour is driven by warped noise, and the lattice is left to
// modulate brightness only.
vec3 filamentColour(float f, vec3 q, float depth) {
	float v = 0.60 * f + 0.10 * depth + 0.30 * vnoise(q * uFilHueScale);
	float hue = fract(uFilHue + uFilHueRange * (v - 0.5));
	return filHSV(vec3(hue, uFilSat, 1.0));
}

// Domain warp: bend the sample point with a low-frequency noise field so the strands kink
// and curl instead of staying straight sine sheets. This is the standard trick for making
// a regular analytic pattern look like it grew rather than was drawn -- without it the
// wave families stay visibly straight. Three vnoise calls per sample; branched out when the
// knob is 0, so it costs nothing to leave off.
vec3 filWarp(vec3 p) {
	float s = uFilWarpScale;
	return (vec3(vnoise(p * s),
	             vnoise(p * s + vec3(17.3, 5.1, 9.7)),
	             vnoise(p * s + vec3(41.7, 23.3, 3.9))) - 0.5) * uFilWarp;
}

// The sample point the ridges see: scaled, and warped if the warp is enabled.
vec3 filWarped(vec3 p) {
	vec3 q = p * uFilScale;
	if (uFilWarp > 0.0) q += filWarp(p);
	return q;
}

// The warp displacement, or zero when the warp is off.
vec3 filDisplace(vec3 p) {
	if (uFilWarp > 0.0) return filWarp(p);
	return vec3(0.0);
}

vec3 nebulaSky(vec3 camPos, vec3 dir, float pxPerDir, float dither, out vec3 transmittance) {
	vec3 d = normalize(dir);

	int steps = int(uFilSteps);
	float dt = uFilView / float(steps);
	float dist = dt * dither;          // per-pixel dither of the first step (see gyroid-clouds)

	vec3 col = vec3(0.0);
	vec3 T = vec3(1.0);

	for (int i = 0; i < FIL_MAX_STEPS; i++) {
		if (i >= steps) break;
		vec3 p = camPos + dist * d;

		// The warp is computed ONCE and used for BOTH the density field and the light lattice.
		// Everything the colour reads has to inherit it, or the parts that do not stay straight
		// and show through as straight colour bands. The lattice in particular was evaluated in
		// raw world space -- `mod(p + 2.5, 5.0)` -- and its axis-aligned cell boundaries are
		// literally straight lines: invisible at a tight hue range, plainly visible once the
		// range is widened.
		vec3 wv = filDisplace(p);
		float f = filamentField(p * uFilScale + wv);

		// Voids are the default; strands are where the field is high.
		float dens = smoothstep(uFilVoid, uFilVoid + 0.25, f);
		dens += uFilCore * smoothstep(0.80, 1.00, f);   // extra-bright cores

		if (dens > 0.0) {
			// Brightness still gets the local-light character, but note this is ONLY brightness:
			// the creases of this lattice are straight, which is why the hue no longer reads from it.
			vec3 lp = mod(p + wv + 2.5, 5.0) - 2.5;
			float ldist = max(length(lp), 1e-3);
			float depth = clamp(dist / max(uFilView, 1.0), 0.0, 1.0);

			vec3 e = filamentColour(f, p * uFilScale + wv, depth) / (1.0 + ldist * ldist * 0.35);
			// Extinction is separate from emission so the gas can GLOW without OCCLUDING.
			// uFilOpacity 1.0 is physically balanced; lower it for a translucent nebula
			// you can see through. (Careful: less extinction means the ray no longer hits
			// the early-out, so a very translucent setting runs every step and costs more.)
			vec3 sigma = FIL_ABSORB * dens * uFilDensity * uFilOpacity;
			vec3 tr = exp(-sigma * dt);

			col += T * e * dens * uFilBright * dt;
			T *= tr;
			if (T.r < 0.003 && T.g < 0.003 && T.b < 0.003) break;
		}
		dist += dt;
	}

	// Standalone backdrop: whatever shows through the gas. The layer contract says a layer
	// returns only its OWN emission, and in the compositor that is right -- the star field is
	// composited behind it and this must stay black there, or the background gets counted
	// twice. It exists so the shader is not stuck against pure black when run on its own in
	// glslviewer / SHADERed / the lab. Default black.
	col += uFilBg * T;

	transmittance = T;
	return col;
}

#endif  // RIDGED_CLOUDS_GLSLINC
// volumetric_starfield.inc.glsl — a starfield you can FLY THROUGH.
//
// `Space/Starfield` is a DOME: every star sits on the celestial sphere at radius=cells, so it
// never moves relative to the viewer. That is correct for distant stars (their parallax is
// unmeasurable) but it means flying gives no sense of travel at all.
//
// This layer is a VOLUME: stars sit on a world-anchored lattice around the viewer, so passing
// them produces real parallax and near ones sweep by quickly.
//
// It is deliberately LOCAL -- the march stops at uStvView. Beyond that the dome takes over.
// That split is not just cheap, it is necessary: a star is a point source, so its ANGULAR size
// is constant, which means the cylinder a single pixel sweeps out has radius
// (angular size x distance) and GROWS without limit. Past some range that cylinder is wider
// than a cell, and any one-cell-per-step test starts missing stars that are near the ray but
// in a neighbouring cell. Bounded, that cannot happen, and distant stars are the dome's job
// anyway -- where parallax is genuinely negligible.
//
// Contract (same shape as the nebula layers):
//     vec3 volumetricStarfieldSky(vec3 camPos, vec3 dir, float pxPerDir, float dither, out vec3 transmittance);
// Stars absorb nothing, so transmittance is always 1 -- exactly like the dome.
//
// GPL-3.0 (see LICENSE at the repository root).

#ifndef VOLUMETRIC_STARFIELD_GLSLINC
#define VOLUMETRIC_STARFIELD_GLSLINC

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/noise.glsl — value noise and fbm, built on lib/hash.glsl.
//
// Requires hash13() to be included first.
//
// GPL-3.0 (see LICENSE at the repository root).

// low-frequency value noise (once per pixel is plenty at these frequencies)

#ifndef LIB_NOISE_GLSL
#define LIB_NOISE_GLSL

float vnoise(vec3 p) {
	vec3 i = floor(p), f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float n = 0.0;
	for (int z = 0; z < 2; z++)
	for (int y = 0; y < 2; y++)
	for (int x = 0; x < 2; x++) {
		vec3 o = vec3(float(x), float(y), float(z));
		n += hash13(i + o) * (mix(1.0 - f.x, f.x, o.x)
		                    * mix(1.0 - f.y, f.y, o.y)
		                    * mix(1.0 - f.z, f.z, o.z));
	}
	return n;
}
float fbm3(vec3 p) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 3; i++) { s += a * vnoise(p); t += a; p *= 2.03; a *= 0.5; }
	return s / t;
}


#endif  // LIB_NOISE_GLSL
// lib/raymarch.glsl — helpers for raymarched volumetric layers.
//
// Pure maths with no host assumptions: camera basis, ray/box intersection, phase
// functions, and a texture-free dither. Included (inlined) by Tools/build_*.glsl.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_RAYMARCH_GLSL
#define LIB_RAYMARCH_GLSL

#ifndef PI
#define PI 3.141592653589793
#endif

// Slab-method ray/AABB intersection (DomNomNom). Returns (tNear, tFar) in ray units;
// there is no hit when tNear > tFar.
vec2 intersectAABB(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax) {
	vec3 tMin = (bmin - ro) / rd;
	vec3 tMax = (bmax - ro) / rd;
	vec3 t1 = min(tMin, tMax);
	vec3 t2 = max(tMin, tMax);
	return vec2(max(max(t1.x, t1.y), t1.z), min(min(t2.x, t2.y), t2.z));
}

// Henyey-Greenstein phase function. g in (-1, 1): negative scatters back, positive
// forward. mu is the cosine between the view ray and the light direction.
float hgPhase(float g, float cosTheta) {
	return (1.0 / (4.0 * PI)) * ((1.0 - g * g) / pow(1.0 + g * g - 2.0 * g * cosTheta, 1.5));
}

// Interleaved gradient noise: a cheap per-pixel dither, used to offset the first ray
// step so the marching does not band. No blue-noise texture needed, so it works in
// every host (SHADERed, glslviewer, Godot).
float ign(vec2 fragCoord) {
	return fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
}

// Camera basis: columns are right, up, -forward, so a view-space ray (forward is -Z)
// maps into world space. `fwd` is the direction the camera looks.
mat3 lookAt(vec3 fwd, vec3 up) {
	vec3 zaxis = normalize(fwd);
	vec3 xaxis = normalize(cross(zaxis, up));
	vec3 yaxis = cross(xaxis, zaxis);
	return mat3(xaxis, yaxis, -zaxis);
}


#endif  // LIB_RAYMARCH_GLSL


#define STV_MAX_STEPS 640   // hard cap on the march

// Star colour: hotter (bluer) for the bright ones, cooler for the dim, which is the usual
// cheap approximation of spectral type.
vec3 starTint(float m) {
	return mix(vec3(1.00, 0.82, 0.66), vec3(0.78, 0.86, 1.00), clamp(m, 0.0, 1.0));
}

vec3 volumetricStarfieldSky(vec3 camPos, vec3 dir, float pxPerDir, float dither, out vec3 transmittance) {
	vec3 d = normalize(dir);
	transmittance = vec3(1.0);            // stars do not absorb

	// Step at HALF a cell so the ray cannot stride over a whole cell, and evaluate a cell only
	// when the ray ENTERS it (tracked via `lastCell`). That dedup is what stops a star being
	// counted once per step. A 3D DDA would be exact; this is the cheap version, and at
	// half-cell steps the only cells it can miss are the ones clipped at a corner.
	float dt = max(uStvCell, 1e-4) * 0.5;
	int steps = min(int(uStvView / dt) + 1, STV_MAX_STEPS);

	vec3 col = vec3(0.0);
	vec3 lastCell = vec3(-1e9);            // guaranteed != the first cell

	for (int i = 0; i < STV_MAX_STEPS; i++) {
		if (i >= steps) break;
		float t = (float(i) + dither) * dt;
		vec3 p = camPos + d * t;

		vec3 c = floor(p / uStvCell);
		if (c == lastCell) continue;
		lastCell = c;

		vec3 r = hash33(c + uStvSeed);
		if (r.x > uStvDensity) continue;    // this cell holds no star
		float mag = r.y;

		// The position MUST come from an independent hash. It used to reuse r.x, which is also
		// the occupancy test, so occupancy (r.x <= density) clamped the star's z offset: at
		// density 0.5 the z offset could only ever land in [0.15, 0.50]. Every occupied cell was
		// therefore empty in its upper z half -- periodic empty slabs, which read as straight
		// layers of sky with no stars. Measured offline: mean z offset 0.324, not 0.500.
		vec3 r2 = hash33(c + uStvSeed + 13.71);

		// The star must sit far enough inside its cell that the ray always visits that cell:
		// a pixel's capture cylinder has radius (uStvAng * distance) at the far end of the
		// volume, and a star closer to the wall than that could be within catching distance
		// while the ray never enters the star's own cell -- so it would be missed. DERIVING the
		// margin keeps that empty shell as thin as the geometry allows; a fixed generous margin
		// leaves periodic empty slabs, which is the artefact we just removed.
		float margin = clamp(uStvAng * uStvView / max(uStvCell, 1e-4), 0.02, 0.45);
		vec3 P = (c + margin + (1.0 - 2.0 * margin) * r2) * uStvCell;

		vec3 rel = P - camPos;
		float along = dot(rel, d);
		if (along <= 0.0) continue;         // behind us

		float dperp = length(rel - along * d);
		float ang = dperp / along;          // angular offset from this pixel's ray

		float rr = uStvAng * (0.95 + 0.45 * mag);                    // constant ANGULAR radius

		if (ang >= rr) continue;

		// Sub-pixel stars fade rather than being lost or fattened, so the field stays
		// resolution-independent -- the same rule as the dome.
		float radPx = rr / max(pxPerDir, 1e-9);
		float cover = clamp(radPx, 0.0, 1.0);

		// Disc falloff, then inverse-square: flying towards a star makes it brighter.
		float q = 1.0 - ang / rr;
		float flux = q * q * cover * cover / (1.0 + along * along * uStvFalloff);

		col += uStvBright * (0.30 + 0.70 * mag) * flux * starTint(mag);
	}

	return col;
}

#endif  // VOLUMETRIC_STARFIELD_GLSLINC

vec3 aces(vec3 x) {
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

void main() {
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;

	// View-space ray straight from the projection matrix (no fov/aspect guesswork),
	// rotated into the world by the inverse view rotation (a transpose).
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	// Dither the first step per pixel: without it, flying forward slides the
	// sampling lattice through the volume and the banding flickers.
	float dither = ign(gl_FragCoord.xy);
	vec3 transmittance;
	vec3 col = vec3(0.0);
	vec3 Tn; vec3 neb   = nebulaSky(uCamPos, dir, pxPerDir, dither, Tn);
	vec3 Ts; vec3 stars = volumetricStarfieldSky(uCamPos, dir, pxPerDir, dither, Ts);
	col = neb + Tn * uStars * stars;

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}
