#version 330
out vec4 outColor;

// GENERATED by Tools/build_nebula.py from the variant's .frag -- do not edit by hand.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed, and
// its GLSL mode is Shadertoy-compatible (iResolution / iMouse / iTime).
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables: driven by SHADERed's own preview camera, so the arcball
// (right-drag / scroll) and the first-person camera actually look around the volume.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

// The knob values live in the .sprj, not here: GLSL uniforms cannot have initialisers,
// which is why SHADERed shows them as variables you can edit (right-click the pass ->
// Variables, then pin them with +).
uniform float uNebDensity;
uniform float uNebHaze;
uniform float uNebStructure;
uniform float uNebBright;
uniform float uNebSunAngle;
uniform float uNebSunHeight;
uniform float uNebNoiseScale;
uniform float uNebVoid;
uniform float uNebView;
uniform float uNebSteps;
uniform float uNebDither;

// ===== PHYSICS ==================================================================
// This variant's constants, shared maths and contract live in gyroid-clouds.glslinc
// (below), so the sky compositor can include the identical code. Nothing to see here.

// ===== SHARED MATHS ===========================================================
// gyroid-clouds.inc.glsl — this variant's constants, shared maths and contract,
// extracted so other shaders (the sky compositor) can include exactly the
// same code. Included by gyroid-clouds.frag and Space/Sky/sky.frag.
// GPL-3.0 (see LICENSE at the repository root).

#ifndef GYROID_CLOUDS_GLSLINC
#define GYROID_CLOUDS_GLSLINC

// ===== PHYSICS ==================================================================
// The gas, the sun and the box. Constants, not sliders.
const vec3  BETA_RAYLEIGH = 100.0 * vec3(0.05802, 0.14558, 0.331);  // Earth-ish air, tweaked
const vec3  BETA_OZONE    = vec3(0.650, 1.881, 0.085);
const vec3  SIGMA_S = 2.0 * BETA_RAYLEIGH;              // scattering
const vec3  SIGMA_A = 4.0 * (BETA_RAYLEIGH + 3.0 * BETA_OZONE);  // absorption
const vec3  SIGMA_E = SIGMA_A;                          // extinction
const float LIGHT_DIST    = 18.0;   // how far the sun ray is marched (no box any more)
const float SUN_POWER     = 200.0;

#define GYROID_OCTAVES 4    // fbm octaves in the density field (cost driver: 6 -> 4)

// ===== SHARED MATHS =============================================================
// Everything from here to the HOST marker is host-independent and is copied verbatim
// into every generated output. Shared maths lives in lib/; the builder inlines the
// includes so generated files stay self-contained. This source runs in glslviewer
// with `-I <repo root>`.

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/raymarch.glsl — helpers for raymarched volumetric layers.
//
// Pure maths with no host assumptions: camera basis, ray/box intersection, phase
// functions, and a texture-free dither. Included (inlined) by Tools/build_*.glsl.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_RAYMARCH_GLSL
#define LIB_RAYMARCH_GLSL

#ifndef PI
#define PI 3.141592653589793
#endif

// Slab-method ray/AABB intersection (DomNomNom). Returns (tNear, tFar) in ray units;
// there is no hit when tNear > tFar.
vec2 intersectAABB(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax) {
	vec3 tMin = (bmin - ro) / rd;
	vec3 tMax = (bmax - ro) / rd;
	vec3 t1 = min(tMin, tMax);
	vec3 t2 = max(tMin, tMax);
	return vec2(max(max(t1.x, t1.y), t1.z), min(min(t2.x, t2.y), t2.z));
}

// Henyey-Greenstein phase function. g in (-1, 1): negative scatters back, positive
// forward. mu is the cosine between the view ray and the light direction.
float hgPhase(float g, float cosTheta) {
	return (1.0 / (4.0 * PI)) * ((1.0 - g * g) / pow(1.0 + g * g - 2.0 * g * cosTheta, 1.5));
}

// Interleaved gradient noise: a cheap per-pixel dither, used to offset the first ray
// step so the marching does not band. No blue-noise texture needed, so it works in
// every host (SHADERed, glslviewer, Godot).
float ign(vec2 fragCoord) {
	return fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
}

// Camera basis: columns are right, up, -forward, so a view-space ray (forward is -Z)
// maps into world space. `fwd` is the direction the camera looks.
mat3 lookAt(vec3 fwd, vec3 up) {
	vec3 zaxis = normalize(fwd);
	vec3 xaxis = normalize(cross(zaxis, up));
	vec3 yaxis = cross(xaxis, zaxis);
	return mat3(xaxis, yaxis, -zaxis);
}


#endif  // LIB_RAYMARCH_GLSL

//-------------------------------- Shape --------------------------------

// A gyroid is a triply-periodic minimal surface; |...| turns it into a shell, and the
// fbm below stacks rotated copies at falling amplitude to make cloud structure.
float gyroid(vec3 p, float thickness, float bias, float frequency) {
	return clamp(abs(dot(sin(p * 0.5), cos(p.zxy * 1.23) * frequency) - bias) - thickness,
	             0.0, 3.0) / 3.0;
}

float gyroidFbm(vec3 p) {
	const int   octaves = GYROID_OCTAVES;
	const float fbmScale = 1.95;
	float a = PI / float(octaves);
	mat3 m3 = fbmScale * mat3(vec3(cos(a), sin(a), 0.0),
	                          vec3(-sin(a), cos(a), 0.0),
	                          vec3(0.0, 0.0, 1.0));
	float weight = 0.0;
	float amplitude = 1.0;
	float frequency = 1.0;
	float res = 0.0;
	for (int i = 0; i < octaves; i++) {
		res += amplitude * gyroid(p, 0.1, 0.0, frequency);
		p *= m3;
		weight += amplitude;
		amplitude *= (i < 4) ? 0.9 : 0.7;
		frequency *= (i < 3) ? 0.65 : 0.78;
	}
	return clamp(res / weight, 0.0, 1.0);
}

// Density of the gas at a world point. Zero outside the box. Away from the centre the
// noise becomes a haze shell and, sharper, a structure shell -- so we sit in a cavity
// looking out at clouds rather than inside a uniform fog.
// Density of the gas at a world point. UNBOUNDED: there is no box.
//
// The field is a 3D noise function, defined everywhere, so we never meet a wall -- fly in
// any direction and there is always new gas ahead. There is also NO radial shaping: the
// voids come from the noise rather than from a cavity, which is what makes it read as a
// nebula you are inside rather than a shell painted on a box.
float cloudDensity(vec3 p) {
	float n = gyroidFbm(uNebNoiseScale * p);
	// Voids are the default; a cloud is where the noise is high. Both the haze and the
	// structure ride on that mask -- otherwise a term like smoothstep(0.02,0.5,n) is ~1
	// everywhere and the whole volume glows uniformly.
	float cloud = smoothstep(uNebVoid, uNebVoid + 0.22, n);
	float density = cloud * (0.5 * uNebHaze + 0.75 * uNebStructure);
	return uNebDensity * (1e-4 + density);
}

//-------------------------------- Lighting --------------------------------

// Multi-octave scattering (the Frostbite/Hillaire formulation): a few cheaper, broader
// scattering events stand in for the many real ones.
vec3 multipleOctaves(float extinction, float mu, float stepL) {
	vec3 luminance = vec3(0.0);
	const int octaves = 6;   // int, not float: safer across GLSL/Godot loop forms
	float a = 1.0;  // attenuation
	float b = 1.0;  // contribution
	float c = 1.0;  // phase attenuation
	for (int i = 0; i < octaves; i++) {
		float phase = mix(hgPhase(-0.1 * c, mu), hgPhase(0.3 * c, mu), 0.7);
		luminance += b * phase * exp(-stepL * extinction * SIGMA_E * a);
		a *= 0.3;
		b *= 0.5;
		c *= 0.5;
	}
	return luminance;
}

// Light reaching p from the sun, by marching a short ray toward it and applying
// Beers-Law, blended with the powder effect for backlighting.
vec3 lightRay(vec3 p, float mu, vec3 sunDirection) {
	// No bounds: the sun ray just marches a fixed distance -- far enough for the gas to
	// occlude it, which is all the shadowing needs.
	float lightRayDistance = LIGHT_DIST;
	// Fewer shadow steps than before: each one is a full density sample, and this is the
	// inner loop of the whole shader.
	int lsteps = max(2, int(uNebSteps * 0.15));
	float stepL = lightRayDistance / float(lsteps);
	float lightRayDensity = 0.0;
	for (int j = 0; j < lsteps; j++) {
		lightRayDensity += cloudDensity(p + sunDirection * float(j) * stepL);
	}
	vec3 beersLaw = multipleOctaves(lightRayDensity, mu, stepL);
	return mix(beersLaw * 2.0 * (1.0 - exp(-stepL * lightRayDensity * 2.0 * SIGMA_E)),
	           beersLaw, 0.5 + 0.5 * mu);
}

//-------------------------------- Raymarching --------------------------------

// Colour along one view ray, and the transmittance of everything in front of what is
// behind the volume (so distant stars can be composed in).
vec3 mainRay(vec3 org, vec3 dir, vec3 sunDirection, out vec3 totalTransmittance,
             float offset) {
	totalTransmittance = vec3(1.0);
	vec3 colour = vec3(0.0);

	// UNBOUNDED -- no box and no intersection to find. The gas is a 3D noise field defined
	// everywhere, so we always start at the camera and march a fixed visible depth: every
	// step is new gas wherever we are. Fly forever, fresh clouds ahead.
	int steps = int(uNebSteps);
	float stepS = uNebView / float(steps);
	float dist  = stepS * offset;
	vec3 p = org + dist * dir;

	float mu = dot(dir, sunDirection);
	float phaseFunction = mix(hgPhase(-0.3, mu), hgPhase(0.3, mu), 0.7);
	vec3 sunLight = vec3(SUN_POWER);

	for (int i = 0; i < steps; i++) {
		float density = cloudDensity(p);
		if (density > 0.0) {
			vec3 sampleSigmaS = SIGMA_S * density;
			vec3 sampleSigmaE = SIGMA_E * density;

			// Lit only by the sun. There is deliberately NO in-volume star field here: the
			// stars are the compositor's business (Space/Starfield), and a 27-cell star
			// scan per march step was the most expensive thing in this shader.
			vec3 luminance = sunLight * phaseFunction * lightRay(p, mu, sunDirection);
			luminance *= sampleSigmaS;

			vec3 transmittance = exp(-sampleSigmaE * stepS);

			// Energy-conserving in-scattering integration (Frostbite 5.6).
			colour += totalTransmittance * (luminance - luminance * transmittance) / sampleSigmaE;
			totalTransmittance *= transmittance;

			if (totalTransmittance.r + totalTransmittance.g + totalTransmittance.b <= 0.003) {
				totalTransmittance = vec3(0.0);
				return colour;
			}
		}
		dist += stepS;
		p = org + dir * dist;
	}
	return colour;
}

// ===== THE CONTRACT =============================================================
// `dither` offsets the first step per pixel (0..1). Without it the samples sit at fixed
// distances from the CAMERA, so flying forward slides the whole sampling lattice through the
// gas and the banding flickers. Dithering turns that into fixed grain instead.
vec3 nebulaSky(vec3 camPos, vec3 dir, float pxPerDir, float dither, out vec3 transmittance) {
	vec3 d = normalize(dir);
	vec3 sunDirection = normalize(vec3(cos(uNebSunAngle), uNebSunHeight, sin(uNebSunAngle)));
	vec3 colour = mainRay(camPos, d, sunDirection, transmittance, dither * uNebDither);
	return colour * uNebBright;
}

#endif  // GYROID_CLOUDS_GLSLINC

vec3 aces(vec3 x) {
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

void main() {
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;

	// View-space ray straight from the projection matrix (no fov/aspect guesswork),
	// rotated into the world by the inverse view rotation (a transpose).
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	// Dither the first step per pixel (see nebulaSky): without it, flying forward slides the
	// sampling lattice through the gas and the banding flickers.
	float dither = ign(gl_FragCoord.xy);
	vec3 transmittance;
	vec3 col = nebulaSky(uCamPos, dir, pxPerDir, dither, transmittance);

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}
