#version 330
out vec4 outColor;

// GENERATED by Tools/build_starfield.py via Tools/shader_build.py from /home/evert/Software/Projects/Shaders/Space/Starfield/starfield.frag -- do not edit by hand.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed, and its
// GLSL mode is Shadertoy-compatible (iResolution / iMouse / iTime).
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables: driven by SHADERed's own preview camera.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

// The knob values live in the .sprj, not here: GLSL uniforms cannot have initialisers,
// which is why SHADERed shows them as variables you can edit (right-click the pass ->
// Variables, then pin them with +).
uniform float uStarSize;
uniform float uStarFieldSize;
uniform float uStarDensity;
uniform float uStarCluster;
uniform float uStarClusterScale;
uniform float uStarBright;
uniform float uStarGlow;
uniform float uStarCount;

// ===== PHYSICS ==================================================================
// The starfield's constants, shared maths and contract live in starfield.glslinc
// (below), so the sky compositor can include the identical code. Nothing to see here.

// ===== SHARED MATHS ===========================================================
// starfield.inc.glsl — the starfield's constants, shared maths and contract,
// extracted so other shaders (the sky compositor) can include exactly the
// same code. Included by starfield.frag and Space/Sky/sky.frag.
// GPL-3.0 (see LICENSE at the repository root).

#ifndef STARFIELD_GLSLINC
#define STARFIELD_GLSLINC

// ===== PHYSICS ==================================================================
// Constants: these describe stars, not taste. They are the same in every host, so
// they are NOT exposed as sliders.
const float STAR_ANG   = 0.0013;  // star angular radius, in DIRECTION UNITS (not pixels).
                                  // The smallest star is uStarFieldSize x this; uStarSize
                                  // scales them all. A star below a pixel is just not seen.
const float MAGNITUDE  = 2.60;  // power law: higher = more faint stars, rarer bright
const float GLOW_SCALE = 2.20;  // radius of the glare disc, x the star radius (tight)
const float GLOW_POW   = 10.0;  // how sharply glare concentrates on the brightest
const float GLOW_GAIN  = 1.40;  // glare peak: brilliant, not a dim wide blob
const float P2         = 2.00;  // density multipliers of the 2nd and 3rd populations
const float P3         = 4.30;
const float W1         = 1.00;  // their weights
const float W2         = 0.80;
const float W3         = 0.55;

// ===== SHARED MATHS =============================================================
// Everything from here to the HOST marker is host-independent and is copied verbatim
// into every generated output. Shared maths lives in lib/; the builder inlines the
// includes so generated files stay self-contained. This source runs in glslviewer
// with `-I <repo root>`.

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/noise.glsl — value noise and fbm, built on lib/hash.glsl.
//
// Requires hash13() to be included first.
//
// GPL-3.0 (see LICENSE at the repository root).

// low-frequency value noise (once per pixel is plenty at these frequencies)

#ifndef LIB_NOISE_GLSL
#define LIB_NOISE_GLSL

float vnoise(vec3 p) {
	vec3 i = floor(p), f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float n = 0.0;
	for (int z = 0; z < 2; z++)
	for (int y = 0; y < 2; y++)
	for (int x = 0; x < 2; x++) {
		vec3 o = vec3(float(x), float(y), float(z));
		n += hash13(i + o) * (mix(1.0 - f.x, f.x, o.x)
		                    * mix(1.0 - f.y, f.y, o.y)
		                    * mix(1.0 - f.z, f.z, o.z));
	}
	return n;
}
float fbm3(vec3 p) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 3; i++) { s += a * vnoise(p); t += a; p *= 2.03; a *= 0.5; }
	return s / t;
}


#endif  // LIB_NOISE_GLSL

// Star colour by TEMPERATURE, cool -> hot: ~2500 K (deep orange) through sun-like to
// ~30000 K (blue). Real stars are overwhelmingly cool dwarfs, but the ones that stand
// out are hot and blue-white, so the sampled temperature is biased up by magnitude.
vec3 starColour(float t) {
	vec3 c0 = vec3(1.00, 0.58, 0.32);  // 2500 K  deep orange
	vec3 c1 = vec3(1.00, 0.72, 0.53);  // 3500 K
	vec3 c2 = vec3(1.00, 0.83, 0.71);  // 4500 K
	vec3 c3 = vec3(1.00, 0.95, 0.90);  // 5800 K  sun-like
	vec3 c4 = vec3(0.92, 0.94, 1.00);  // 7000 K
	vec3 c5 = vec3(0.80, 0.85, 1.00);  // 11000 K
	vec3 c6 = vec3(0.68, 0.76, 1.00);  // 30000 K blue
	if (t < 0.20) return mix(c0, c1, t / 0.20);
	if (t < 0.40) return mix(c1, c2, (t - 0.20) / 0.20);
	if (t < 0.60) return mix(c2, c3, (t - 0.40) / 0.20);
	if (t < 0.75) return mix(c3, c4, (t - 0.60) / 0.15);
	if (t < 0.90) return mix(c4, c5, (t - 0.75) / 0.15);
	return mix(c5, c6, (t - 0.90) / 0.10);
}

// clusterField: the star-specific wrapper on the shared fbm3 (lib/noise.glsl).
float clusterField(vec3 dir) {
	if (uStarCluster <= 0.0) return 0.0;
	return (fbm3(dir * uStarClusterScale + 3.0) - 0.5) * 2.0;
}

// One population of stars.
//   cells : lattice density      pxDir : direction units per PIXEL
//   count : cell occupancy       seed  : decorrelates the populations
vec3 starPopulation(vec3 dir, float cells, float pxDir, float count, float seed) {
	vec3 p    = dir * cells;
	vec3 base = floor(p);
	vec3 fr   = p - base;
	vec3 acc  = vec3(0.0);

	// A neighbouring cell matters only when this pixel is within a star radius of the
	// shared face -- rare, since the radius is ~1 px and a cell is tens of px wide.
	// That is what avoids clipped stars without paying for 27 cells every pixel.
	// Angular size, NOT pixels: a star smaller than a pixel is simply not seen, so the
	// display's resolution thins the field by itself. This also makes the culling below
	// resolution-independent (it used to scale with pxDir and drop stars as res rose).
	float rrMax = uStarSize * (uStarFieldSize + 1.5) * STAR_ANG * cells;

	for (int ox = -1; ox <= 1; ox++) {
		if (float(ox) == -1.0 && fr.x >= rrMax) continue;
		if (float(ox) ==  1.0 && 1.0 - fr.x >= rrMax) continue;
		for (int oy = -1; oy <= 1; oy++) {
			if (float(oy) == -1.0 && fr.y >= rrMax) continue;
			if (float(oy) ==  1.0 && 1.0 - fr.y >= rrMax) continue;
			for (int oz = -1; oz <= 1; oz++) {
				if (float(oz) == -1.0 && fr.z >= rrMax) continue;
				if (float(oz) ==  1.0 && 1.0 - fr.z >= rrMax) continue;

				vec3 c = base + vec3(float(ox), float(oy), float(oz));
				if (hash13(c + seed) > count) continue;      // no star in this cell

				vec3 P = c + 0.15 + 0.70 * hash33(c + seed * 1.7);

				float m   = pow(hash13(c + seed * 3.1), MAGNITUDE);
				// uStarSize scales every star; uStarFieldSize sets the faint end; brighter
				// stars (larger m) are drawn larger.
				float grow = uStarSize * (uStarFieldSize + 1.5 * m) * STAR_ANG;
				float rr   = max(grow * cells, 1e-9);

				float t    = length(p - P) / rr;
				float core = max(0.0, 1.0 - t);
				float b    = core * core * (0.80 + 7.20 * m);

				// GLARE. A bright point spreads into a disc by scattering in the eye and
				// atmosphere -- real optics, not an effect. Weighted by a steep power of
				// the magnitude so only the few brightest stars get it.
				if (uStarGlow > 0.0) {
					float th   = length(p - P) / (rr * GLOW_SCALE);
					float halo = max(0.0, 1.0 - th);
					b += uStarGlow * GLOW_GAIN * pow(halo, 5.0) * pow(m, GLOW_POW);
				}

				// temperature, biased hotter for the brighter stars
				float tp  = clamp(pow(hash13(c + seed * 5.3), 1.4) + 0.40 * m, 0.0, 1.0);
				vec3 tint = starColour(tp);

				// Hue-preserving normalisation: letting the channels CLIP turns every
				// bright star white, so normalise to a unit peak instead.
				vec3 contrib = tint * b;
				float pk = max(max(contrib.r, contrib.g), contrib.b);
				if (pk > 1.0) contrib /= pk;

				acc += contrib;
			}
		}
	}
	return acc;
}

// ===== THE CONTRACT =============================================================
vec3 starfieldSky(vec3 dir, float pxPerDir, out vec3 transmittance) {
	vec3 d = normalize(dir);

	float cl  = clusterField(d);
	float occ = clamp(uStarCount * (1.0 + uStarCluster * cl), 0.05, 1.0);

	vec3 col = vec3(0.0);
	col += starPopulation(d, uStarDensity,      pxPerDir, occ,        0.0) * W1;
	col += starPopulation(d, uStarDensity * P2, pxPerDir, occ * 0.60, 17.0) * W2;
	col += starPopulation(d, uStarDensity * P3, pxPerDir, occ * 0.35, 43.0) * W3;

	transmittance = vec3(1.0);  // the starfield is the base layer: it absorbs nothing
	return col * uStarBright;
}

#endif  // STARFIELD_GLSLINC

vec3 aces(vec3 x) {
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

void main() {
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;

	// View-space ray straight from the projection matrix (no fov/aspect guesswork),
	// rotated into the world by the inverse view rotation (a transpose).
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	vec3 transmittance;
	vec3 col = vec3(0.0);
	col = starfieldSky(dir, pxPerDir, transmittance);

	outColor = vec4(col, 1.0);
}
