#version 330
out vec4 outColor;

// GENERATED by Tools/build_sky.py from Space/Sky/sky.frag -- do not edit by hand.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed.
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables: its own preview camera drives the ray.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

uniform float uFadeNebula;
uniform float uFadeStars;
uniform float uFadeGalaxy;
uniform float uStarDensity;
uniform float uStarCluster;
uniform float uStarClusterScale;
uniform float uStarBright;
uniform float uStarGlow;
uniform float uStarCount;
uniform float uNebDensity;
uniform float uNebHaze;
uniform float uNebStructure;
uniform float uNebBright;
uniform float uNebSunAngle;
uniform float uNebSunHeight;
uniform float uNebLocalStars;
uniform float uNebNoiseScale;
uniform float uNebSteps;
uniform float uGalPitch;
uniform float uGalYaw;
uniform float uGalCoreAngle;
uniform float uGalWidth;
uniform float uGalCoreSize;
uniform float uGalCore;
uniform float uGalBand;
uniform float uGalStarClouds;
uniform float uGalNoiseScale;
uniform float uGalRiftOffset;
uniform float uGalRiftWidth;
uniform float uGalDust;
uniform float uGalBright;

// ===== PHYSICS ==================================================================
// The compositor has no physics of its own; the layers bring theirs via their includes.

// ===== SHARED MATHS =============================================================
// The layers themselves. Each include brings its constants, maths and contract; the
// include guards let them share lib/hash.glsl without colliding.

// starfield.inc.glsl — the starfield's constants, shared maths and contract,
// extracted so other shaders (the sky compositor) can include exactly the
// same code. Included by starfield.frag and Space/Sky/sky.frag.
// GPL-3.0 (see LICENSE at the repository root).

#ifndef STARFIELD_GLSLINC
#define STARFIELD_GLSLINC

// ===== PHYSICS ==================================================================
// Constants: these describe stars, not taste. They are the same in every host, so
// they are NOT exposed as sliders.
const float STAR_SIZE  = 1.10;  // star radius in pixels at the low-magnitude end
const float MAGNITUDE  = 2.60;  // power law: higher = more faint stars, rarer bright
const float GLOW_SCALE = 2.20;  // radius of the glare disc, x the star radius (tight)
const float GLOW_POW   = 10.0;  // how sharply glare concentrates on the brightest
const float GLOW_GAIN  = 1.40;  // glare peak: brilliant, not a dim wide blob
const float P2         = 2.00;  // density multipliers of the 2nd and 3rd populations
const float P3         = 4.30;
const float W1         = 1.00;  // their weights
const float W2         = 0.80;
const float W3         = 0.55;

// ===== SHARED MATHS =============================================================
// Everything from here to the HOST marker is host-independent and is copied verbatim
// into every generated output. Shared maths lives in lib/; the builder inlines the
// includes so generated files stay self-contained. This source runs in glslviewer
// with `-I <repo root>`.

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/noise.glsl — value noise and fbm, built on lib/hash.glsl.
//
// Requires hash13() to be included first.
//
// GPL-3.0 (see LICENSE at the repository root).

// low-frequency value noise (once per pixel is plenty at these frequencies)

#ifndef LIB_NOISE_GLSL
#define LIB_NOISE_GLSL

float vnoise(vec3 p) {
	vec3 i = floor(p), f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float n = 0.0;
	for (int z = 0; z < 2; z++)
	for (int y = 0; y < 2; y++)
	for (int x = 0; x < 2; x++) {
		vec3 o = vec3(float(x), float(y), float(z));
		n += hash13(i + o) * (mix(1.0 - f.x, f.x, o.x)
		                    * mix(1.0 - f.y, f.y, o.y)
		                    * mix(1.0 - f.z, f.z, o.z));
	}
	return n;
}
float fbm3(vec3 p) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 3; i++) { s += a * vnoise(p); t += a; p *= 2.03; a *= 0.5; }
	return s / t;
}


#endif  // LIB_NOISE_GLSL

// Star colour by TEMPERATURE, cool -> hot: ~2500 K (deep orange) through sun-like to
// ~30000 K (blue). Real stars are overwhelmingly cool dwarfs, but the ones that stand
// out are hot and blue-white, so the sampled temperature is biased up by magnitude.
vec3 starColour(float t) {
	vec3 c0 = vec3(1.00, 0.58, 0.32);  // 2500 K  deep orange
	vec3 c1 = vec3(1.00, 0.72, 0.53);  // 3500 K
	vec3 c2 = vec3(1.00, 0.83, 0.71);  // 4500 K
	vec3 c3 = vec3(1.00, 0.95, 0.90);  // 5800 K  sun-like
	vec3 c4 = vec3(0.92, 0.94, 1.00);  // 7000 K
	vec3 c5 = vec3(0.80, 0.85, 1.00);  // 11000 K
	vec3 c6 = vec3(0.68, 0.76, 1.00);  // 30000 K blue
	if (t < 0.20) return mix(c0, c1, t / 0.20);
	if (t < 0.40) return mix(c1, c2, (t - 0.20) / 0.20);
	if (t < 0.60) return mix(c2, c3, (t - 0.40) / 0.20);
	if (t < 0.75) return mix(c3, c4, (t - 0.60) / 0.15);
	if (t < 0.90) return mix(c4, c5, (t - 0.75) / 0.15);
	return mix(c5, c6, (t - 0.90) / 0.10);
}

// clusterField: the star-specific wrapper on the shared fbm3 (lib/noise.glsl).
float clusterField(vec3 dir) {
	if (uStarCluster <= 0.0) return 0.0;
	return (fbm3(dir * uStarClusterScale + 3.0) - 0.5) * 2.0;
}

// One population of stars.
//   cells : lattice density      pxDir : direction units per PIXEL
//   count : cell occupancy       seed  : decorrelates the populations
vec3 starPopulation(vec3 dir, float cells, float pxDir, float count, float seed) {
	vec3 p    = dir * cells;
	vec3 base = floor(p);
	vec3 fr   = p - base;
	vec3 acc  = vec3(0.0);

	// A neighbouring cell matters only when this pixel is within a star radius of the
	// shared face -- rare, since the radius is ~1 px and a cell is tens of px wide.
	// That is what avoids clipped stars without paying for 27 cells every pixel.
	float rrMax = STAR_SIZE * 1.45 * pxDir * cells;

	for (int ox = -1; ox <= 1; ox++) {
		if (float(ox) == -1.0 && fr.x >= rrMax) continue;
		if (float(ox) ==  1.0 && 1.0 - fr.x >= rrMax) continue;
		for (int oy = -1; oy <= 1; oy++) {
			if (float(oy) == -1.0 && fr.y >= rrMax) continue;
			if (float(oy) ==  1.0 && 1.0 - fr.y >= rrMax) continue;
			for (int oz = -1; oz <= 1; oz++) {
				if (float(oz) == -1.0 && fr.z >= rrMax) continue;
				if (float(oz) ==  1.0 && 1.0 - fr.z >= rrMax) continue;

				vec3 c = base + vec3(float(ox), float(oy), float(oz));
				if (hash13(c + seed) > count) continue;      // no star in this cell

				vec3 P = c + 0.15 + 0.70 * hash33(c + seed * 1.7);

				float m   = pow(hash13(c + seed * 3.1), MAGNITUDE);
				float rpx = STAR_SIZE * (0.95 + 0.45 * m);
				float rr  = max(rpx * pxDir * cells, 1e-9);

				float t    = length(p - P) / rr;
				float core = max(0.0, 1.0 - t);
				float b    = core * core * (0.80 + 7.20 * m);

				// GLARE. A bright point spreads into a disc by scattering in the eye and
				// atmosphere -- real optics, not an effect. Weighted by a steep power of
				// the magnitude so only the few brightest stars get it.
				if (uStarGlow > 0.0) {
					float th   = length(p - P) / (rr * GLOW_SCALE);
					float halo = max(0.0, 1.0 - th);
					b += uStarGlow * GLOW_GAIN * pow(halo, 5.0) * pow(m, GLOW_POW);
				}

				// temperature, biased hotter for the brighter stars
				float tp  = clamp(pow(hash13(c + seed * 5.3), 1.4) + 0.40 * m, 0.0, 1.0);
				vec3 tint = starColour(tp);

				// Hue-preserving normalisation: letting the channels CLIP turns every
				// bright star white, so normalise to a unit peak instead.
				vec3 contrib = tint * b;
				float pk = max(max(contrib.r, contrib.g), contrib.b);
				if (pk > 1.0) contrib /= pk;

				acc += contrib;
			}
		}
	}
	return acc;
}

// ===== THE CONTRACT =============================================================
vec3 starfieldSky(vec3 dir, float pxPerDir, out vec3 transmittance) {
	vec3 d = normalize(dir);

	float cl  = clusterField(d);
	float occ = clamp(uStarCount * (1.0 + uStarCluster * cl), 0.05, 1.0);

	vec3 col = vec3(0.0);
	col += starPopulation(d, uStarDensity,      pxPerDir, occ,        0.0) * W1;
	col += starPopulation(d, uStarDensity * P2, pxPerDir, occ * 0.60, 17.0) * W2;
	col += starPopulation(d, uStarDensity * P3, pxPerDir, occ * 0.35, 43.0) * W3;

	transmittance = vec3(1.0);  // the starfield is the base layer: it absorbs nothing
	return col * uStarBright;
}

#endif  // STARFIELD_GLSLINC
// gyroid-clouds.inc.glsl — this variant's constants, shared maths and contract,
// extracted so other shaders (the sky compositor) can include exactly the
// same code. Included by gyroid-clouds.frag and Space/Sky/sky.frag.
// GPL-3.0 (see LICENSE at the repository root).

#ifndef GYROID_CLOUDS_GLSLINC
#define GYROID_CLOUDS_GLSLINC

// ===== PHYSICS ==================================================================
// The gas, the sun and the box. Constants, not sliders.
const vec3  BETA_RAYLEIGH = 100.0 * vec3(0.05802, 0.14558, 0.331);  // Earth-ish air, tweaked
const vec3  BETA_OZONE    = vec3(0.650, 1.881, 0.085);
const vec3  SIGMA_S = 2.0 * BETA_RAYLEIGH;              // scattering
const vec3  SIGMA_A = 4.0 * (BETA_RAYLEIGH + 3.0 * BETA_OZONE);  // absorption
const vec3  SIGMA_E = SIGMA_A;                          // extinction
const float VOLUME_EXTENT = 10.0;                       // half-size of the cube
const float SUN_POWER     = 200.0;

#define GYROID_OCTAVES 6    // fbm octaves in the density field (cost driver)

// ===== SHARED MATHS =============================================================
// Everything from here to the HOST marker is host-independent and is copied verbatim
// into every generated output. Shared maths lives in lib/; the builder inlines the
// includes so generated files stay self-contained. This source runs in glslviewer
// with `-I <repo root>`.

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/raymarch.glsl — helpers for raymarched volumetric layers.
//
// Pure maths with no host assumptions: camera basis, ray/box intersection, phase
// functions, and a texture-free dither. Included (inlined) by Tools/build_*.glsl.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_RAYMARCH_GLSL
#define LIB_RAYMARCH_GLSL

#ifndef PI
#define PI 3.141592653589793
#endif

// Slab-method ray/AABB intersection (DomNomNom). Returns (tNear, tFar) in ray units;
// there is no hit when tNear > tFar.
vec2 intersectAABB(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax) {
	vec3 tMin = (bmin - ro) / rd;
	vec3 tMax = (bmax - ro) / rd;
	vec3 t1 = min(tMin, tMax);
	vec3 t2 = max(tMin, tMax);
	return vec2(max(max(t1.x, t1.y), t1.z), min(min(t2.x, t2.y), t2.z));
}

// Henyey-Greenstein phase function. g in (-1, 1): negative scatters back, positive
// forward. mu is the cosine between the view ray and the light direction.
float hgPhase(float g, float cosTheta) {
	return (1.0 / (4.0 * PI)) * ((1.0 - g * g) / pow(1.0 + g * g - 2.0 * g * cosTheta, 1.5));
}

// Interleaved gradient noise: a cheap per-pixel dither, used to offset the first ray
// step so the marching does not band. No blue-noise texture needed, so it works in
// every host (SHADERed, glslviewer, Godot).
float ign(vec2 fragCoord) {
	return fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
}

// Camera basis: columns are right, up, -forward, so a view-space ray (forward is -Z)
// maps into world space. `fwd` is the direction the camera looks.
mat3 lookAt(vec3 fwd, vec3 up) {
	vec3 zaxis = normalize(fwd);
	vec3 xaxis = normalize(cross(zaxis, up));
	vec3 yaxis = cross(xaxis, zaxis);
	return mat3(xaxis, yaxis, -zaxis);
}


#endif  // LIB_RAYMARCH_GLSL

//-------------------------------- Shape --------------------------------

// A gyroid is a triply-periodic minimal surface; |...| turns it into a shell, and the
// fbm below stacks rotated copies at falling amplitude to make cloud structure.
float gyroid(vec3 p, float thickness, float bias, float frequency) {
	return clamp(abs(dot(sin(p * 0.5), cos(p.zxy * 1.23) * frequency) - bias) - thickness,
	             0.0, 3.0) / 3.0;
}

float gyroidFbm(vec3 p) {
	const int   octaves = GYROID_OCTAVES;
	const float fbmScale = 1.95;
	float a = PI / float(octaves);
	mat3 m3 = fbmScale * mat3(vec3(cos(a), sin(a), 0.0),
	                          vec3(-sin(a), cos(a), 0.0),
	                          vec3(0.0, 0.0, 1.0));
	float weight = 0.0;
	float amplitude = 1.0;
	float frequency = 1.0;
	float res = 0.0;
	for (int i = 0; i < octaves; i++) {
		res += amplitude * gyroid(p, 0.1, 0.0, frequency);
		p *= m3;
		weight += amplitude;
		amplitude *= (i < 4) ? 0.9 : 0.7;
		frequency *= (i < 3) ? 0.65 : 0.78;
	}
	return clamp(res / weight, 0.0, 1.0);
}

// Density of the gas at a world point. Zero outside the box. Away from the centre the
// noise becomes a haze shell and, sharper, a structure shell -- so we sit in a cavity
// looking out at clouds rather than inside a uniform fog.
float cloudDensity(vec3 p) {
	if (p.x < -VOLUME_EXTENT || p.x > VOLUME_EXTENT ||
	    p.y < -VOLUME_EXTENT || p.y > VOLUME_EXTENT ||
	    p.z < -VOLUME_EXTENT || p.z > VOLUME_EXTENT) {
		return 0.0;
	}
	float n = gyroidFbm(uNebNoiseScale * p);
	float r = length(p);
	float structure = smoothstep(3.0, 5.0, r) * smoothstep(0.05, 0.10, n) * uNebStructure;
	float haze      = smoothstep(2.0, 10.0, r) * smoothstep(0.02, 0.50, n) * uNebHaze;
	return uNebDensity * (3e-4 + 0.5 * haze + 0.75 * structure);
}

//-------------------------------- Local stars --------------------------------

// Star colour by temperature, as a cosine palette (Inigo Quilez).
vec3 starTint(float t) {
	vec3 a = vec3(0.65);
	vec3 b = 1.0 - a;
	vec3 c = vec3(1.0);
	vec3 d = vec3(0.15, 0.5, 0.75);
	return pow(a + b * cos(2.0 * PI * (c * t + d)), vec3(2.2));
}

// One star per cell near p, with a tight glow. These are LOCAL stars -- inside the gas
// volume, not on the distant dome -- so the gas can occlude them and they can light it.
vec3 localStars(vec3 p) {
	p *= 0.2;
	vec3 bestRand = vec3(0.0);
	vec3 bestCell = vec3(0.0);
	float best = 1e10;
	for (int x = -1; x <= 1; x++)
	for (int y = -1; y <= 1; y++)
	for (int z = -1; z <= 1; z++) {
		vec3 c = floor(p) + vec3(float(x), float(y), float(z));
		vec3 h = 2.0 * hash33(c) - 1.0;          // in [-1, 1]
		vec3 f = c + 0.5 + 0.5 * h;
		float dd = length(p - f);
		if (dd < best) { best = dd; bestRand = h; bestCell = c; }
	}
	vec3 r1 = clamp(0.5 + 0.5 * bestRand, 0.0, 1.0);
	vec3 r2 = clamp(0.5 + 0.5 * (2.0 * hash33(bestCell + vec3(3.12, 104.9, -9.5)) - 1.0),
	                0.0, 1.0);
	float glow = max(0.0, pow(0.25 / max(best, 1e-5), 2.0));
	return vec3(0.05) * r1.z * step(0.45, r2.z)
	     * mix(vec3(1.0), starTint(r1.y), 0.3)
	     * smoothstep(0.5, 0.0, best) * glow;
}

//-------------------------------- Lighting --------------------------------

// Multi-octave scattering (the Frostbite/Hillaire formulation): a few cheaper, broader
// scattering events stand in for the many real ones.
vec3 multipleOctaves(float extinction, float mu, float stepL) {
	vec3 luminance = vec3(0.0);
	const int octaves = 6;   // int, not float: safer across GLSL/Godot loop forms
	float a = 1.0;  // attenuation
	float b = 1.0;  // contribution
	float c = 1.0;  // phase attenuation
	for (int i = 0; i < octaves; i++) {
		float phase = mix(hgPhase(-0.1 * c, mu), hgPhase(0.3 * c, mu), 0.7);
		luminance += b * phase * exp(-stepL * extinction * SIGMA_E * a);
		a *= 0.3;
		b *= 0.5;
		c *= 0.5;
	}
	return luminance;
}

// Light reaching p from the sun, by marching a short ray toward it and applying
// Beers-Law, blended with the powder effect for backlighting.
vec3 lightRay(vec3 p, float mu, vec3 sunDirection) {
	vec2 hit = intersectAABB(p, sunDirection, vec3(-VOLUME_EXTENT), vec3(VOLUME_EXTENT));
	float lightRayDistance = VOLUME_EXTENT * 0.25;
	if (hit.x < hit.y && hit.y > 0.0) {
		lightRayDistance = hit.y - max(hit.x, 0.0);
	}
	int lsteps = max(3, int(uNebSteps * 0.25));
	float stepL = lightRayDistance / float(lsteps);
	float lightRayDensity = 0.0;
	for (int j = 0; j < lsteps; j++) {
		lightRayDensity += cloudDensity(p + sunDirection * float(j) * stepL);
	}
	vec3 beersLaw = multipleOctaves(lightRayDensity, mu, stepL);
	return mix(beersLaw * 2.0 * (1.0 - exp(-stepL * lightRayDensity * 2.0 * SIGMA_E)),
	           beersLaw, 0.5 + 0.5 * mu);
}

//-------------------------------- Raymarching --------------------------------

// Colour along one view ray, and the transmittance of everything in front of what is
// behind the volume (so distant stars can be composed in).
vec3 mainRay(vec3 org, vec3 dir, vec3 sunDirection, out vec3 totalTransmittance,
             float offset) {
	totalTransmittance = vec3(1.0);
	vec3 colour = vec3(0.0);

	vec2 hit = intersectAABB(org, dir, vec3(-VOLUME_EXTENT), vec3(VOLUME_EXTENT));

	// Start at the camera when it is inside the box, otherwise at the near face.
	bool inside = org.x > -VOLUME_EXTENT && org.x < VOLUME_EXTENT &&
	              org.y > -VOLUME_EXTENT && org.y < VOLUME_EXTENT &&
	              org.z > -VOLUME_EXTENT && org.z < VOLUME_EXTENT;
	float distToStart = inside ? 0.0 : hit.x;
	float distToEnd   = hit.y;
	if (!(distToEnd > distToStart) || distToEnd <= 0.0) return colour;

	int steps = int(uNebSteps);
	float stepS = (distToEnd - distToStart) / float(steps);
	distToStart += stepS * offset;

	float dist = distToStart;
	vec3 p = org + dist * dir;
	float mu = dot(dir, sunDirection);
	float phaseFunction = mix(hgPhase(-0.3, mu), hgPhase(0.3, mu), 0.7);
	vec3 sunLight = vec3(SUN_POWER);

	for (int i = 0; i < steps; i++) {
		float density = cloudDensity(p);
		if (density > 0.0) {
			vec3 sampleSigmaS = SIGMA_S * density;
			vec3 sampleSigmaE = SIGMA_E * density;

			// Local starlight, scaled by how much gas is here (so stars brighten the
			// clouds they sit in, not empty space).
			vec3 ambient = vec3(0.0);
			if (uNebLocalStars > 0.0) {
				ambient = uNebLocalStars * localStars(p);
				ambient *= smoothstep(1e-3, 2e-3, density);
			}

			vec3 luminance = ambient + sunLight * phaseFunction * lightRay(p, mu, sunDirection);
			luminance *= sampleSigmaS;

			vec3 transmittance = exp(-sampleSigmaE * stepS);

			// Energy-conserving in-scattering integration (Frostbite 5.6).
			colour += totalTransmittance * (luminance - luminance * transmittance) / sampleSigmaE;
			totalTransmittance *= transmittance;

			if (totalTransmittance.r + totalTransmittance.g + totalTransmittance.b <= 0.003) {
				totalTransmittance = vec3(0.0);
				return colour;
			}
		}
		dist += stepS;
		p = org + dir * dist;
	}
	return colour;
}

// ===== THE CONTRACT =============================================================
vec3 nebulaSky(vec3 camPos, vec3 dir, float pxPerDir, out vec3 transmittance) {
	vec3 d = normalize(dir);
	vec3 sunDirection = normalize(vec3(cos(uNebSunAngle), uNebSunHeight, sin(uNebSunAngle)));
	vec3 colour = mainRay(camPos, d, sunDirection, transmittance, 0.0);
	return colour * uNebBright;
}

#endif  // GYROID_CLOUDS_GLSLINC
// fbm-milkyway.inc.glsl — the Milky Way band as a direction-only background layer.
//
// We are INSIDE the galaxy, so the band is not symmetric: it is brighter toward the
// galactic core, thinner and dimmer toward the anticenter, and cut by a dust rift just
// off the midplane. The masks below build that; the texture is value-noise fbm, which is
// far cheaper than the scattered-sphere primitives the reference used.
//
// Extracted so the sky compositor can include exactly the same code. Included by
// fbm-milkyway.frag and Space/Sky/sky.frag.
//
// GPL-3.0 (see LICENSE at the repository root).

#ifndef FBM_MILKYWAY_INC_GLSL
#define FBM_MILKYWAY_INC_GLSL

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/noise.glsl — value noise and fbm, built on lib/hash.glsl.
//
// Requires hash13() to be included first.
//
// GPL-3.0 (see LICENSE at the repository root).

// low-frequency value noise (once per pixel is plenty at these frequencies)

#ifndef LIB_NOISE_GLSL
#define LIB_NOISE_GLSL

float vnoise(vec3 p) {
	vec3 i = floor(p), f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float n = 0.0;
	for (int z = 0; z < 2; z++)
	for (int y = 0; y < 2; y++)
	for (int x = 0; x < 2; x++) {
		vec3 o = vec3(float(x), float(y), float(z));
		n += hash13(i + o) * (mix(1.0 - f.x, f.x, o.x)
		                    * mix(1.0 - f.y, f.y, o.y)
		                    * mix(1.0 - f.z, f.z, o.z));
	}
	return n;
}
float fbm3(vec3 p) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 3; i++) { s += a * vnoise(p); t += a; p *= 2.03; a *= 0.5; }
	return s / t;
}


#endif  // LIB_NOISE_GLSL
// lib/raymarch.glsl — helpers for raymarched volumetric layers.
//
// Pure maths with no host assumptions: camera basis, ray/box intersection, phase
// functions, and a texture-free dither. Included (inlined) by Tools/build_*.glsl.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_RAYMARCH_GLSL
#define LIB_RAYMARCH_GLSL

#ifndef PI
#define PI 3.141592653589793
#endif

// Slab-method ray/AABB intersection (DomNomNom). Returns (tNear, tFar) in ray units;
// there is no hit when tNear > tFar.
vec2 intersectAABB(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax) {
	vec3 tMin = (bmin - ro) / rd;
	vec3 tMax = (bmax - ro) / rd;
	vec3 t1 = min(tMin, tMax);
	vec3 t2 = max(tMin, tMax);
	return vec2(max(max(t1.x, t1.y), t1.z), min(min(t2.x, t2.y), t2.z));
}

// Henyey-Greenstein phase function. g in (-1, 1): negative scatters back, positive
// forward. mu is the cosine between the view ray and the light direction.
float hgPhase(float g, float cosTheta) {
	return (1.0 / (4.0 * PI)) * ((1.0 - g * g) / pow(1.0 + g * g - 2.0 * g * cosTheta, 1.5));
}

// Interleaved gradient noise: a cheap per-pixel dither, used to offset the first ray
// step so the marching does not band. No blue-noise texture needed, so it works in
// every host (SHADERed, glslviewer, Godot).
float ign(vec2 fragCoord) {
	return fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
}

// Camera basis: columns are right, up, -forward, so a view-space ray (forward is -Z)
// maps into world space. `fwd` is the direction the camera looks.
mat3 lookAt(vec3 fwd, vec3 up) {
	vec3 zaxis = normalize(fwd);
	vec3 xaxis = normalize(cross(zaxis, up));
	vec3 yaxis = cross(xaxis, zaxis);
	return mat3(xaxis, yaxis, -zaxis);
}


#endif  // LIB_RAYMARCH_GLSL

// value-noise fbm with a variable octave count (for the band's cloud texture)
float mwFbm(vec3 p, float octaves) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 5; i++) {
		if (float(i) >= octaves) break;
		s += a * vnoise(p);
		t += a;
		p *= 2.03;
		a *= 0.5;
	}
	return s / max(t, 1e-5);
}

// The galactic frame from the knobs: `pole` is the band normal (the plane is where
// dot(dir, pole) == 0), and `coreDir` is where the bright core sits in that plane.
vec3 mwGalacticFrame(out vec3 coreDir) {
	float cp = cos(uGalPitch);
	vec3 pole = normalize(vec3(sin(uGalPitch) * cos(uGalYaw), cp, sin(uGalPitch) * sin(uGalYaw)));
	vec3 up = abs(pole.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
	vec3 x = normalize(cross(pole, up));
	vec3 y = cross(pole, x);
	coreDir = normalize(cos(uGalCoreAngle) * x + sin(uGalCoreAngle) * y);
	return pole;
}

vec3 galacticBandSky(vec3 dir, float pxPerDir, out vec3 transmittance) {
	vec3 d = normalize(dir);

	vec3 coreDir;
	vec3 pole = mwGalacticFrame(coreDir);

	float b = dot(d, pole);        // height above the galactic plane
	float l = dot(d, coreDir);     // longitude: +1 toward the core, -1 anticenter

	// Brighter toward the core, dimmer toward the anticenter: we are off to one side.
	float asym = 0.35 + 0.65 * smoothstep(-1.0, 1.0, l);

	// The band: thin, and thinner away from the core.
	float width = uGalWidth * (0.5 + 0.75 * smoothstep(-1.0, 1.0, l));
	float band = exp(-(b * b) / (width * width));

	// Cloudy texture inside the band, then a finer granular layer for star clouds.
	float clouds = mwFbm(d * uGalNoiseScale, 4.0);
	float nebulosity = band * mix(0.45, 1.0, clouds) * asym;
	float grain = smoothstep(0.55, 0.95, mwFbm(d * uGalNoiseScale * 4.0, 3.0));
	float starClouds = band * grain * asym;

	// The core bulge.
	float cosang = clamp(dot(d, coreDir), -1.0, 1.0);
	float ang = acos(cosang);
	float core = exp(-(ang * ang) / (uGalCoreSize * uGalCoreSize));

	// Dust: a rift just off the midplane, deepest toward the core.
	float rift = exp(-pow((b - uGalRiftOffset) / uGalRiftWidth, 2.0)) * (0.3 + 0.7 * smoothstep(-1.0, 1.0, l));
	vec3 dustAbs = vec3(0.72, 0.84, 1.0);
	vec3 T = exp(-dustAbs * uGalDust * rift);

	vec3 col = vec3(0.0);
	col += core * vec3(1.00, 0.93, 0.80) * uGalCore;
	col += nebulosity * vec3(0.70, 0.80, 1.00) * uGalBand;
	col += starClouds * vec3(0.85, 0.90, 1.00) * uGalStarClouds;
	col *= T;   // dust carves dark lanes through the band itself

	transmittance = T;
	return col * uGalBright;
}

#endif  // FBM_MILKYWAY_INC_GLSL

// ===== THE FOLD =================================================================
vec3 skyColour(vec3 camPos, vec3 dir, float pxPerDir, out vec3 transmittance) {
	vec3 col = vec3(0.0);
	vec3 T   = vec3(1.0);

	// ---- nearest: the local nebula volume (emission AND absorption) ----
	// Guarded on the fade: at 0 the whole layer is skipped, so turning the clouds off
	// costs nothing at all rather than evaluating an invisible layer.
	if (uFadeNebula > 0.0) {
		vec3 Tl;
		vec3 e = nebulaSky(camPos, dir, pxPerDir, Tl);
		Tl = mix(vec3(1.0), Tl, uFadeNebula);
		col += T * e * uFadeNebula;
		T *= Tl;
	}
	if (T.r < 0.01 && T.g < 0.01 && T.b < 0.01) { transmittance = T; return col; }

	// ---- the local starfield dome ----
	{
		vec3 Tl;
		vec3 e = starfieldSky(dir, pxPerDir, Tl);
		Tl = mix(vec3(1.0), Tl, uFadeStars);
		col += T * e * uFadeStars;
		T *= Tl;
	}
	if (T.r < 0.01 && T.g < 0.01 && T.b < 0.01) { transmittance = T; return col; }

	// ---- farthest: background content ----
	// The Milky Way band is direction-only and sits behind everything above, so its own
	// dust cannot dim the local stars in front of it -- but it also cannot be dimmed by
	// them, and the fold is the same one line.
	if (uFadeGalaxy > 0.0) {
		vec3 Tl;
		vec3 e = galacticBandSky(dir, pxPerDir, Tl);
		Tl = mix(vec3(1.0), Tl, uFadeGalaxy);
		col += T * e * uFadeGalaxy;
		T *= Tl;
	}

	transmittance = T;
	return col;
}

vec3 aces(vec3 x) {
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

void main() {
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	vec3 transmittance;
	vec3 col = skyColour(uCamPos, dir, pxPerDir, transmittance);

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}
