#!/usr/bin/env python3
"""build_starfield.py — generate every host format of the starfield base layer.

    Space/Starfield/starfield.frag   the canonical source (also the glslviewer build)
        |
        +-- starfield.glsl          SHADERed / Shadertoy-style
        +-- starfield.sprj          SHADERed project (carries the slider values)
        +-- starfield.gdshader      Godot 4 spatial shader for a sky sphere

The source is split on its section markers, so the maths is written exactly once:

    // ===== PHYSICS     constants, copied verbatim into every output
    // ===== VARIABLES   the knobs; each annotated "[min, max] description"
    // ===== SHARED      maths + the contract, copied verbatim
    // ===== HOST        host-specific plumbing, REPLACED per host

The source may `#include "lib/foo.glsl"` (paths relative to the repo root). Those are
inlined into every generated output, so the outputs stay self-contained -- SHADERed
and Godot consumers do not resolve our include paths.

Usage:
    python3 Tools/build_starfield.py            # generate + verify
    python3 Tools/build_starfield.py --check    # verify only

GLSL outputs are verified with glslangValidator when it is installed (it checks GLSL
without needing a GPU). The Godot output is checked structurally -- its boilerplate is
Godot's own dialect, which glslangValidator cannot parse.
"""

import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTDIR = os.path.join(ROOT, "Space", "Starfield")
SOURCE = os.path.join(OUTDIR, "starfield.frag")

# SHADERed face order, GL/DDS convention, for reference cubemap objects:
#   left = -X   right = +X   top = +Y   bottom = -Y   front = -Z   back = +Z

INCLUDE_RE = re.compile(r'^[ \t]*#include[ \t]+"([^"]+)"[ \t]*$', re.M)


def resolve_includes(text):
    """Inline `#include "path"` lines, paths relative to the repo root.

    Generated outputs must be self-contained: SHADERed and Godot consumers do not
    resolve our include paths, so inlining happens here rather than at the host.
    Includes nest; canonical sources run in glslviewer with `-I <repo root>`.
    """
    def repl(m):
        path = os.path.join(ROOT, m.group(1))
        if not os.path.isfile(path):
            raise SystemExit("include not found: %s" % path)
        with open(path) as f:
            return resolve_includes(f.read()).rstrip()
    return INCLUDE_RE.sub(repl, text)


def read_source():
    with open(SOURCE) as f:
        lines = resolve_includes(f.read()).split("\n")

    def find(prefix):
        for i, ln in enumerate(lines):
            if ln.startswith(prefix):
                return i
        raise SystemExit("marker not found in source: %r" % prefix)

    i_phys = find("// ===== PHYSICS")
    i_vars = find("// ===== VARIABLES")
    i_shared = find("// ===== SHARED MATHS")
    i_host = find("// ===== HOST")

    physics = "\n".join(lines[i_phys:i_vars]).rstrip()
    shared = "\n".join(lines[i_shared:i_host]).rstrip()

    # VARIABLES: `const float name = value;  // [min, max] description`
    pat = re.compile(
        r"^const\s+float\s+(\w+)\s*=\s*([-\d.]+)\s*;\s*(?://\s*)?(?:\[([^\]]+)\]\s*)?(.*)$")
    variables = []
    for ln in lines[i_vars:i_shared]:
        m = pat.match(ln.strip())
        if m:
            name, value, rng, note = m.groups()
            lo = hi = None
            if rng:
                parts = [p.strip() for p in rng.split(",")]
                if len(parts) == 2:
                    lo, hi = float(parts[0]), float(parts[1])
            variables.append({"name": name, "value": value,
                              "min": lo, "max": hi, "note": (note or "").strip()})
    if not variables:
        raise SystemExit("no variables parsed -- check the annotations")
    return physics, shared, variables


def godot_step(lo, hi):
    """A sensible hint_range step: a power of ten about 1/100 of the range."""
    import math
    span = max(hi - lo, 1e-6)
    return 10.0 ** math.floor(math.log10(span / 100.0))


def emit_shadered(physics, shared, variables):
    uni = "\n".join("uniform float %s;" % v["name"] for v in variables)
    return f"""#version 330
out vec4 outColor;

// GENERATED by Tools/build_starfield.py from starfield.frag -- do not edit by hand.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed, and
// its GLSL mode is Shadertoy-compatible (iResolution / iMouse / iTime).
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// The knob values live in starfield.sprj, not here: GLSL uniforms cannot have
// initialisers, which is why SHADERed shows them as variables you can edit.
{uni}

{physics}

{shared}

void main() {{
	vec2 uv  = (gl_FragCoord.xy - 0.5 * iResolution) / iResolution.y;
	vec3 dir = normalize(vec3(uv, 1.4));

	// direction units per pixel: 2*tan(fov/2)/height, with fov ~71 degrees
	float pxPerDir = 1.0 / (1.4 * iResolution.y);

	float transmittance;
	outColor = vec4(starfieldSky(dir, pxPerDir, transmittance), 1.0);
}}
"""


def emit_sprj(variables):
    var_xml = "".join(
        '\n\t\t\t\t<variable type="float" name="%s">\n'
        '\t\t\t\t\t<row><value>%s</value></row>\n'
        '\t\t\t\t</variable>' % (v["name"], v["value"]) for v in variables)
    return f"""<?xml version="1.0"?>
<project version="2">
\t<pipeline>
\t\t<pass name="Starfield" type="shader" active="true" patchverts="1">
\t\t\t<shader type="vs" path="starfield.vert" entry="main" />
\t\t\t<shader type="ps" path="starfield.glsl" entry="main" />
\t\t\t<inputlayout>
\t\t\t\t<item value="Position" semantic="POSITION" />
\t\t\t\t<item value="Normal" semantic="NORMAL" />
\t\t\t\t<item value="Texcoord" semantic="TEXCOORD0" />
\t\t\t</inputlayout>
\t\t\t<rendertexture />
\t\t\t<items>
\t\t\t\t<item name="FS" type="geometry">
\t\t\t\t\t<type>ScreenQuad</type>
\t\t\t\t\t<width>1</width>
\t\t\t\t\t<height>1</height>
\t\t\t\t\t<depth>1</depth>
\t\t\t\t\t<topology>TriangleList</topology>
\t\t\t\t</item>
\t\t\t</items>
\t\t\t<itemvalues />
\t\t\t<variables>
\t\t\t\t<variable type="float4x4" name="matVP" system="Orthographic" />
\t\t\t\t<variable type="float4x4" name="matGeo" system="GeometryTransform" />
\t\t\t\t<variable type="float2" name="iResolution" system="ViewportSize" />
\t\t\t\t<variable type="float2" name="iMouse" system="MousePosition" />
\t\t\t\t<variable type="float" name="iTime" system="Time" />{var_xml}
\t\t\t</variables>
\t\t\t<macros />
\t\t</pass>
\t</pipeline>
\t<objects />
\t<cameras />
\t<settings>
\t\t<entry type="property" name="Starfield" item="pipe" />
\t\t<entry type="file" name="Starfield" shader="vs" />
\t\t<entry type="file" name="Starfield" shader="ps" />
\t\t<entry type="camera" fp="false">
\t\t\t<distance>19</distance>
\t\t\t<pitch>89</pitch>
\t\t\t<yaw>3</yaw>
\t\t\t<roll>360</roll>
\t\t</entry>
\t\t<entry type="clearcolor" r="0" g="0" b="0" a="1" />
\t\t<entry type="usealpha" val="false" />
\t</settings>
\t<plugindata />
</project>
"""


VERT = """#version 330
uniform mat4 matVP;
uniform mat4 matGeo;

layout (location = 0) in vec3 pos;
layout (location = 1) in vec3 normal;

void main() {
	gl_Position = matVP * matGeo * vec4(pos, 1);
}
"""


def emit_godot(physics, shared, variables):
    uni = "\n".join(
        "uniform float %s : hint_range(%.6g, %.6g, %.6g) = %s;  // %s"
        % (v["name"], v["min"], v["max"], godot_step(v["min"], v["max"]), v["value"], v["note"])
        if v["min"] is not None else
        "uniform float %s = %s;  // %s" % (v["name"], v["value"], v["note"])
        for v in variables)
    return f"""// GENERATED by Tools/build_starfield.py from starfield.frag -- do not edit by hand.
// Godot 4 spatial shader for a sky sphere: an inverted sphere (cull_front) with the
// camera at its centre. Attach to a MeshInstance3D SphereMesh of any large radius.
//
// The host must set uPxPerDir -- the direction-units-per-pixel of the current view --
// because star size is specified in PIXELS. From GDScript, on ready and on resize:
//
//     var h := max(get_viewport().get_visible_rect().size.y, 1.0)
//     mat.set_shader_parameter("uPxPerDir", 2.0 * tan(deg_to_rad(cam.fov * 0.5)) / h)
shader_type spatial;
render_mode cull_front, unshaded, depth_draw_never, depth_test_disabled;

{uni}

// Host plumbing: set by the scene, not a user knob.
uniform float uPxPerDir : hint_range(0.00005, 0.02, 0.00005) = 0.0013;

{physics}

{shared}

varying vec3 v_dir;

// CRITICAL: compute the world direction in vertex(). Inside fragment(), VERTEX is in
// VIEW space, so transforming it by MODEL_MATRIX there gives a value that never
// changes when the camera rotates -- the sky would be painted on the screen.
void vertex() {{
	v_dir = (MODEL_MATRIX * vec4(VERTEX, 0.0)).xyz;
}}

void fragment() {{
	float transmittance;
	ALBEDO = starfieldSky(normalize(v_dir), uPxPerDir, transmittance);
}}
"""


def verify(path, is_glsl):
    if not is_glsl:
        return "structural"
    if not shutil.which("glslangValidator"):
        return "skipped (no glslangValidator)"
    r = subprocess.run(["glslangValidator", path], capture_output=True, text=True)
    errs = [l for l in (r.stdout + r.stderr).split("\n") if "ERROR" in l]
    if errs:
        return "FAILED:\n    " + "\n    ".join(errs[:5])
    return "OK"


def main():
    check_only = "--check" in sys.argv
    physics, shared, variables = read_source()
    print("source : %s" % os.path.relpath(SOURCE, ROOT))
    print("physics: %d lines, shared: %d lines, variables: %d"
          % (physics.count("\n") + 1, shared.count("\n") + 1, len(variables)))

    outputs = [
        ("starfield.glsl",     emit_shadered(physics, shared, variables), True),
        ("starfield.sprj",     emit_sprj(variables),                      False),
        ("starfield.vert",     VERT,                                      True),
        ("starfield.gdshader", emit_godot(physics, shared, variables),    False),
    ]

    if not check_only:
        for name, text, _ in outputs:
            with open(os.path.join(OUTDIR, name), "w") as f:
                f.write(text)
        print("wrote  : %s" % ", ".join(n for n, _, _ in outputs))

    print("verify :")
    bad = 0
    for name, _, is_glsl in outputs:
        res = verify(os.path.join(OUTDIR, name), is_glsl)
        if res.startswith("FAILED"):
            bad += 1
        print("    %-20s %s" % (name, res))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
