#!/usr/bin/env python3
"""build_sky.py — generate every host format of the sky compositor (Space/Sky/sky.frag).

A single shader, not a family. For now it borrows the generic plumbing (include
inlining, marker parsing, the SHADERed project, verification) from build_nebula.py rather
than duplicating it; if a fourth builder turns up, that plumbing should move into
Tools/shader_build.py.

    python3 Tools/build_sky.py            # generate + verify
    python3 Tools/build_sky.py --check    # verify only
"""

import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("build_nebula", os.path.join(HERE, "build_nebula.py"))
nb = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(nb)

OUTDIR = os.path.join(nb.ROOT, "Space", "Sky")
SOURCE = os.path.join(OUTDIR, "sky.frag")


def emit_shadered(physics, shared, variables):
    uni = "\n".join(nb.decl(v) for v in variables)
    return f"""#version 330
out vec4 outColor;

// GENERATED by Tools/build_sky.py from Space/Sky/sky.frag -- do not edit by hand.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed.
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables: its own preview camera drives the ray.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

{uni}

{physics}

{shared}

vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

void main() {{
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	float dither = ign(gl_FragCoord.xy);
	vec3 transmittance;
	vec3 col = skyColour(uCamPos, dir, pxPerDir, dither, transmittance);

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}}
"""


def emit_godot(physics, shared, variables):
    uni = "\n".join(nb.godot_uniform(v) for v in variables)
    return f"""// GENERATED by Tools/build_sky.py from Space/Sky/sky.frag -- do not edit by hand.
// Godot 4 spatial shader for a sky sphere. Attach to a MeshInstance3D SphereMesh.
//
// The host must set uCamPos to the camera's world position and uPxPerDir on ready /
// on resize.
shader_type spatial;
render_mode cull_front, unshaded, depth_draw_never, depth_test_disabled;

{uni}

uniform vec3  uCamPos = vec3(0.0, 0.0, 0.0);
uniform float uPxPerDir : hint_range(0.00005, 0.02, 0.00005) = 0.0013;

{physics}

{shared}

varying vec3 v_dir;

vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

void vertex() {{
	v_dir = (MODEL_MATRIX * vec4(VERTEX, 0.0)).xyz;
}}

void fragment() {{
	vec3 dir = normalize(v_dir);
	float dither = ign(FRAGCOORD.xy);
	vec3 transmittance;
	vec3 col = skyColour(uCamPos, dir, uPxPerDir, dither, transmittance);
	col = aces(col);
	ALBEDO = pow(col, vec3(0.4545));
}}
"""


def main():
    check_only = "--check" in sys.argv
    physics, shared, variables = nb.read_source(SOURCE)
    outputs = [
        ("sky.glsl",     emit_shadered(physics, shared, variables), "frag"),
        ("sky.sprj",     nb.emit_sprj(variables, "sky"),            None),
        ("sky.vert",     nb.VERT,                                   "vert"),
        ("sky.gdshader", emit_godot(physics, shared, variables),    None),
    ]
    print("source : Space/Sky/sky.frag")
    print("variables: %d" % len(variables))
    bad = 0
    if not check_only:
        for name, text, _ in outputs:
            with open(os.path.join(OUTDIR, name), "w") as f:
                f.write(text)
        print("wrote  : %s" % ", ".join(n for n, _, _ in outputs))
    print("verify :")
    for name, _, stage in outputs:
        res = nb.verify(os.path.join(OUTDIR, name), stage)
        if res.startswith("FAILED"):
            bad += 1
        print("    %-14s %s" % (name, res))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
