#!/usr/bin/env python3
"""build_nebula.py — generate every host format of every nebula variant.

    Space/Nebula/<variant>.frag     canonical source (also the glslviewer build)
        |
        +-- <variant>.glsl          SHADERed / Shadertoy-style
        +-- <variant>.sprj          SHADERed project (carries the slider values)
        +-- <variant>.gdshader      Godot 4 spatial shader for a sky sphere

Every `*.frag` in Space/Nebula/ is treated as a variant; the variant name is the file
stem, so it lives in every generated filename. The source is split on its section
markers (see build_starfield.py, which this mirrors) and may `#include "lib/..."`.

    python3 Tools/build_nebula.py            # generate + verify all variants
    python3 Tools/build_nebula.py --check    # verify only

This shares its pattern with build_starfield.py rather than a module, for now; if a
third builder appears, the common plumbing should move into Tools/shader_build.py.
"""

import glob
import math
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTDIR = os.path.join(ROOT, "Space", "Nebula")

INCLUDE_RE = re.compile(r'^[ \t]*#include[ \t]+"([^"]+)"[ \t]*$', re.M)


def resolve_includes(text):
    """Inline `#include "path"` lines, paths relative to the repo root."""
    def repl(m):
        path = os.path.join(ROOT, m.group(1))
        if not os.path.isfile(path):
            raise SystemExit("include not found: %s" % path)
        with open(path) as f:
            return resolve_includes(f.read()).rstrip()
    return INCLUDE_RE.sub(repl, text)


VAR_RE = re.compile(
    r"^const\s+float\s+(\w+)\s*=\s*([-\d.]+)\s*;\s*(?://\s*)?(?:\[([^\]]+)\]\s*)?(.*)$")


def read_source(path):
    with open(path) as f:
        lines = resolve_includes(f.read()).split("\n")

    def find(prefix):
        for i, ln in enumerate(lines):
            if ln.startswith(prefix):
                return i
        raise SystemExit("marker not found in %s: %r" % (path, prefix))

    i_phys = find("// ===== PHYSICS")
    i_vars = find("// ===== VARIABLES")
    i_shared = find("// ===== SHARED MATHS")
    i_host = find("// ===== HOST")

    physics = "\n".join(lines[i_phys:i_vars]).rstrip()
    shared = "\n".join(lines[i_shared:i_host]).rstrip()

    variables = []
    for ln in lines[i_vars:i_shared]:
        m = VAR_RE.match(ln.strip())
        if m:
            name, value, rng, note = m.groups()
            lo = hi = None
            if rng:
                parts = [p.strip() for p in rng.split(",")]
                if len(parts) == 2:
                    lo, hi = float(parts[0]), float(parts[1])
            variables.append({"name": name, "value": value,
                              "min": lo, "max": hi, "note": (note or "").strip()})
    if not variables:
        raise SystemExit("no variables parsed in %s -- check the annotations" % path)
    return physics, shared, variables


def godot_step(lo, hi):
    span = max(hi - lo, 1e-6)
    return 10.0 ** math.floor(math.log10(span / 100.0))


def emit_shadered(physics, shared, variables):
    uni = "\n".join("uniform float %s;" % v["name"] for v in variables)
    return f"""#version 330
out vec4 outColor;

// GENERATED by Tools/build_nebula.py from the variant's .frag -- do not edit by hand.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed, and
// its GLSL mode is Shadertoy-compatible (iResolution / iMouse / iTime).
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables: driven by SHADERed's own preview camera, so the arcball
// (right-drag / scroll) and the first-person camera actually look around the volume.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

// The knob values live in the .sprj, not here: GLSL uniforms cannot have initialisers,
// which is why SHADERed shows them as variables you can edit (right-click the pass ->
// Variables, then pin them with +).
{uni}

{physics}

{shared}

vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

void main() {{
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;

	// View-space ray straight from the projection matrix (no fov/aspect guesswork),
	// rotated into the world by the inverse view rotation (a transpose).
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	// Dither the first step per pixel (see nebulaSky): without it, flying forward slides the
	// sampling lattice through the gas and the banding flickers.
	float dither = ign(gl_FragCoord.xy);
	vec3 transmittance;
	vec3 col = nebulaSky(uCamPos, dir, pxPerDir, dither, transmittance);

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}}
"""


def emit_sprj(variables, base):
    var_xml = "".join(
        '\n\t\t\t\t<variable type="float" name="%s">\n'
        '\t\t\t\t\t<row><value>%s</value></row>\n'
        '\t\t\t\t</variable>' % (v["name"], v["value"]) for v in variables)
    return f"""<?xml version="1.0"?>
<project version="2">
\t<pipeline>
\t\t<pass name="{base}" type="shader" active="true" patchverts="1">
\t\t\t<shader type="vs" path="{base}.vert" entry="main" />
\t\t\t<shader type="ps" path="{base}.glsl" entry="main" />
\t\t\t<inputlayout>
\t\t\t\t<item value="Position" semantic="POSITION" />
\t\t\t\t<item value="Normal" semantic="NORMAL" />
\t\t\t\t<item value="Texcoord" semantic="TEXCOORD0" />
\t\t\t</inputlayout>
\t\t\t<rendertexture />
\t\t\t<items>
\t\t\t\t<item name="FS" type="geometry">
\t\t\t\t\t<type>ScreenQuad</type>
\t\t\t\t\t<width>1</width>
\t\t\t\t\t<height>1</height>
\t\t\t\t\t<depth>1</depth>
\t\t\t\t\t<topology>TriangleList</topology>
\t\t\t\t</item>
\t\t\t</items>
\t\t\t<itemvalues />
\t\t\t<variables>
\t\t\t\t<variable type="float4x4" name="matVP" system="Orthographic" />
\t\t\t\t<variable type="float4x4" name="matGeo" system="GeometryTransform" />
\t\t\t\t<variable type="float2" name="iResolution" system="ViewportSize" />
\t\t\t\t<variable type="float2" name="iMouse" system="MousePosition" />
\t\t\t\t<variable type="float" name="iTime" system="Time" />
\t\t\t\t<variable type="float4x4" name="uView" system="View" />
\t\t\t\t<variable type="float4x4" name="uProj" system="Projection" />
\t\t\t\t<variable type="float3" name="uCamPos" system="CameraPosition3" />{var_xml}
\t\t\t</variables>
\t\t\t<macros />
\t\t</pass>
\t</pipeline>
\t<objects />
\t<cameras />
\t<settings>
\t\t<entry type="property" name="{base}" item="pipe" />
\t\t<entry type="file" name="{base}" shader="vs" />
\t\t<entry type="file" name="{base}" shader="ps" />
\t\t<entry type="camera" fp="false">
\t\t\t<distance>3</distance>
\t\t\t<pitch>20</pitch>
\t\t\t<yaw>45</yaw>
\t\t\t<roll>360</roll>
\t\t</entry>
\t\t<entry type="clearcolor" r="0" g="0" b="0" a="1" />
\t\t<entry type="usealpha" val="false" />
\t</settings>
\t<plugindata />
</project>
"""


VERT = """#version 330
uniform mat4 matVP;
uniform mat4 matGeo;

layout (location = 0) in vec3 pos;
layout (location = 1) in vec3 normal;

void main() {
	gl_Position = matVP * matGeo * vec4(pos, 1);
}
"""


def emit_godot(physics, shared, variables):
    uni = "\n".join(
        "uniform float %s : hint_range(%.6g, %.6g, %.6g) = %s;  // %s"
        % (v["name"], v["min"], v["max"], godot_step(v["min"], v["max"]), v["value"], v["note"])
        if v["min"] is not None else
        "uniform float %s = %s;  // %s" % (v["name"], v["value"], v["note"])
        for v in variables)
    return f"""// GENERATED by Tools/build_nebula.py from the variant's .frag -- do not edit by hand.
// Godot 4 spatial shader for a sky sphere: an inverted sphere (cull_front) with the
// camera at its centre. Attach to a MeshInstance3D SphereMesh of any large radius.
//
// The host must set uCamPos to the camera's world position (the volume is world-space,
// so this is what gives parallax) and uPxPerDir on ready / on resize.
//
// PROVISIONAL: the volume is world-fixed at the origin, so it is only in view when the
// camera is near it; a real scene would place the volume and pass its transform.
shader_type spatial;
render_mode cull_front, unshaded, depth_draw_never, depth_test_disabled;

{uni}

uniform vec3  uCamPos = vec3(0.0, 0.0, 0.0);
uniform float uPxPerDir : hint_range(0.00005, 0.02, 0.00005) = 0.0013;

{physics}

{shared}

varying vec3 v_dir;

// ACES filmic tone map (Krzysztof Narkowicz). The source keeps this in its HOST
// section, which the builder replaces, so the generated host must carry its own.
vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

// CRITICAL: compute the world direction in vertex(). Inside fragment(), VERTEX is in
// VIEW space, so transforming it by MODEL_MATRIX there gives a value that never
// changes when the camera rotates -- the sky would be painted on the screen.
void vertex() {{
	v_dir = (MODEL_MATRIX * vec4(VERTEX, 0.0)).xyz;
}}

void fragment() {{
	vec3 dir = normalize(v_dir);
	float dither = ign(FRAGCOORD.xy);
	vec3 transmittance;
	vec3 col = nebulaSky(uCamPos, dir, uPxPerDir, dither, transmittance);
	col = aces(col);
	ALBEDO = pow(col, vec3(0.4545));
}}
"""


def verify(path, stage):
    if not stage:
        return "structural"
    if not shutil.which("glslangValidator"):
        return "skipped (no glslangValidator)"
    # glslangValidator only auto-detects the stage from the file extension, and it does
    # NOT recognise `.glsl` -- without -S it prints usage and exits non-zero having
    # compiled nothing, which reads as "pass". Always state the stage explicitly.
    r = subprocess.run(["glslangValidator", "-S", stage, path],
                       capture_output=True, text=True)
    errs = [l for l in (r.stdout + r.stderr).split("\n") if "ERROR" in l]
    if errs or r.returncode != 0:
        detail = errs[:5] or ["exited %d" % r.returncode]
        return "FAILED:\n    " + "\n    ".join(detail)
    return "OK"


def build(base, source, check_only):
    physics, shared, variables = read_source(source)
    outputs = [
        ("%s.glsl"     % base, emit_shadered(physics, shared, variables), "frag"),
        ("%s.sprj"     % base, emit_sprj(variables, base),                None),
        ("%s.vert"     % base, VERT,                                      "vert"),
        ("%s.gdshader" % base, emit_godot(physics, shared, variables),    None),
    ]
    print("\nvariant: %s" % base)
    if not check_only:
        for name, text, _ in outputs:
            with open(os.path.join(OUTDIR, name), "w") as f:
                f.write(text)
        print("wrote  : %s" % ", ".join(n for n, _, _ in outputs))
    bad = 0
    for name, _, stage in outputs:
        res = verify(os.path.join(OUTDIR, name), stage)
        if res.startswith("FAILED"):
            bad += 1
        print("    %-24s %s" % (name, res))
    return bad


def main():
    check_only = "--check" in sys.argv
    sources = sorted(glob.glob(os.path.join(OUTDIR, "*.frag")))
    if not sources:
        raise SystemExit("no variants found in %s" % OUTDIR)
    bad = 0
    for source in sources:
        bad += build(os.path.basename(source)[:-len(".frag")], source, check_only)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
