#!/usr/bin/env python3
"""build_galacticband.py — generate every host format of every GalacticBand variant.

    Space/GalacticBand/<variant>.frag   canonical source (also the glslviewer build)
        |
        +-- <variant>.glsl / .sprj / .vert / .gdshader

Every `*.frag` in Space/GalacticBand/ is a variant, exactly like Space/Nebula/. Borrows
the generic plumbing from build_nebula.py for now.
"""

import glob
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("build_nebula", os.path.join(HERE, "build_nebula.py"))
nb = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(nb)

OUTDIR = os.path.join(nb.ROOT, "Space", "GalacticBand")


def emit_shadered(physics, shared, variables):
    uni = "\n".join("uniform float %s;" % v["name"] for v in variables)
    return f"""#version 330
out vec4 outColor;

// GENERATED by Tools/build_galacticband.py from the variant's .frag -- do not edit.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed.
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

{uni}

{physics}

{shared}

vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

void main() {{
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	vec3 transmittance;
	vec3 col = galacticBandSky(dir, pxPerDir, transmittance);

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}}
"""


def emit_godot(physics, shared, variables):
    uni = "\n".join(
        "uniform float %s : hint_range(%.6g, %.6g, %.6g) = %s;  // %s"
        % (v["name"], v["min"], v["max"], nb.godot_step(v["min"], v["max"]), v["value"], v["note"])
        if v["min"] is not None else
        "uniform float %s = %s;  // %s" % (v["name"], v["value"], v["note"])
        for v in variables)
    return f"""// GENERATED by Tools/build_galacticband.py from the variant's .frag -- do not edit.
// Godot 4 spatial shader for a sky sphere. The host sets uPxPerDir on ready / resize.
shader_type spatial;
render_mode cull_front, unshaded, depth_draw_never, depth_test_disabled;

{uni}

uniform float uPxPerDir : hint_range(0.00005, 0.02, 0.00005) = 0.0013;

{physics}

{shared}

varying vec3 v_dir;

vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

void vertex() {{
	v_dir = (MODEL_MATRIX * vec4(VERTEX, 0.0)).xyz;
}}

void fragment() {{
	vec3 transmittance;
	vec3 col = galacticBandSky(normalize(v_dir), uPxPerDir, transmittance);
	col = aces(col);
	ALBEDO = pow(col, vec3(0.4545));
}}
"""


def build(base, source, check_only):
    physics, shared, variables = nb.read_source(source)
    outputs = [
        ("%s.glsl"     % base, emit_shadered(physics, shared, variables), "frag"),
        ("%s.sprj"     % base, nb.emit_sprj(variables, base),             None),
        ("%s.vert"     % base, nb.VERT,                                   "vert"),
        ("%s.gdshader" % base, emit_godot(physics, shared, variables),    None),
    ]
    print("\nvariant: %s" % base)
    if not check_only:
        for name, text, _ in outputs:
            with open(os.path.join(OUTDIR, name), "w") as f:
                f.write(text)
        print("wrote  : %s" % ", ".join(n for n, _, _ in outputs))
    bad = 0
    for name, _, stage in outputs:
        res = nb.verify(os.path.join(OUTDIR, name), stage)
        if res.startswith("FAILED"):
            bad += 1
        print("    %-24s %s" % (name, res))
    return bad


def main():
    check_only = "--check" in sys.argv
    sources = sorted(glob.glob(os.path.join(OUTDIR, "*.frag")))
    if not sources:
        raise SystemExit("no variants found in %s" % OUTDIR)
    bad = 0
    for source in sources:
        bad += build(os.path.basename(source)[:-len(".frag")], source, check_only)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
