#!/usr/bin/env python3
"""build_scenes.py — generate every host format of every SCENE source.

    Space/Scenes/<name>.frag    canonical source (also the glslviewer build)
        |
        +-- <name>.glsl             SHADERed / Shadertoy-style
        +-- <name>.sprj             SHADERed project (carries the knob values)
        +-- <name>.vet              vertex shader for the .sprj
        +-- <name>.gdshader         Godot 4 spatial shader for a sky sphere

Mirrors build_nebula.py, which owns all of the plumbing this reuses (marker parsing,
include inlining, the SHADERed project, verification) — the only real difference is the
contract function it calls.

    python3 Tools/build_scenes.py            # generate + verify everything
    python3 Tools/build_scenes.py --check    # verify only
"""

import glob
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location("build_nebula", os.path.join(HERE, "build_nebula.py"))
nb = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(nb)

OUTDIR = os.path.join(nb.ROOT, "Space", "Scenes")


def check_knob_drift(source, variables):
    """A scene must declare every knob the layers it includes declare.

    The builders read knob declarations out of the .frag's VARIABLES section, so a scene has
    to REPEAT each layer's knobs -- and that is a drift trap: add or rename a knob in a layer
    and the scene silently stops exposing it (worse, the .sprj and the Godot hints keep the
    stale name and the value goes nowhere). So for every layer .inc.glsl this source includes,
    find that layer's sibling .frag, and require all of its knobs to be present here.
    """
    text = open(source).read()
    have = {v["name"] for v in variables}
    missing = []
    for m in re.finditer(r'#include\s+"([^"]+\.inc\.glsl)"', text):
        inc = m.group(1)
        layer_frag = os.path.join(nb.ROOT, inc[:-len(".inc.glsl")] + ".frag")
        if not os.path.isfile(layer_frag):
            continue
        _, _, layer_vars = nb.read_source(layer_frag)
        for v in layer_vars:
            if v["name"] not in have:
                missing.append("%s (from %s)" % (v["name"], os.path.basename(layer_frag)))
    return missing



def emit_shadered(physics, shared, variables):
    uni = "\n".join(nb.decl(v) for v in variables)
    return f"""#version 330
out vec4 outColor;

// GENERATED by Tools/build_scenes.py from the source's .frag -- do not edit by hand.
// SHADERed build: #version must be the literal first line, and its GLSL mode is
// Shadertoy-compatible (iResolution / iMouse / iTime).
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

// SHADERed system variables, so its preview camera drives the view.
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

// Knob values live in the .sprj: GLSL uniforms cannot have initialisers.
{uni}

{physics}

{shared}

vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

void main() {{
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	// Dither the first step per pixel, or flying forward slides the sampling lattice.
	float dither = ign(gl_FragCoord.xy);
	// The scene: stars behind, nebula in front dimming them by its transmittance.
	vec3 Tn; vec3 neb   = nebulaSky(uCamPos, dir, pxPerDir, dither, Tn);
	vec3 Ts; vec3 stars = volumetricStarfieldSky(uCamPos, dir, pxPerDir, dither, Ts);
	vec3 col = neb + Tn * uStars * stars;

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}}
"""


def emit_godot(physics, shared, variables):
    uni = "\n".join(nb.godot_uniform(v) for v in variables)
    return f"""shader_type spatial;
// GENERATED by Tools/build_scenes.py from the source's .frag -- do not edit by hand.
render_mode unshaded, cull_disabled, depth_draw_never, blend_mix, skip_vertex_transform;

{uni}
uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;
uniform float uPxPerDir;
uniform float uSteps;

{physics}

{shared}

vec3 aces(vec3 x) {{
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}}

varying vec3 v_dir;

void vertex() {{
	// Godot's VERTEX inside fragment() is view space, so the direction is computed here and
	// passed down as a varying. (Trap, and it cost us once.)
	VERTEX = (MODELVIEW_MATRIX * vec4(VERTEX, 1.0)).xyz;
	POSITION = PROJECTION_MATRIX * vec4(VERTEX, 1.0);
	v_dir = normalize((INV_VIEW_MATRIX * vec4(VERTEX, 0.0)).xyz);
}}

void fragment() {{
	float dither = ign(FRAGCOORD.xy);
	vec3 Tn; vec3 neb   = nebulaSky(uCamPos, normalize(v_dir), uPxPerDir, dither, Tn);
	vec3 Ts; vec3 stars = volumetricStarfieldSky(uCamPos, normalize(v_dir), uPxPerDir, dither, Ts);
	vec3 col = neb + Tn * uStars * stars;
	ALBEDO = pow(aces(col), vec3(0.4545));
}}
"""


def check_host_has_shared(path, shared):
    """Catch a host emitter that forgot to emit {shared}.

    The structural check passed a .gdshader whose shared maths was MISSING ENTIRELY -- the
    emit simply never interpolated {physics}/{shared}, so the file had no functions in it and
    Godot failed with "No matching function found for: 'ign'". "Looks structurally fine" is
    not "has the code in it". So: every function the shared section defines must appear in the
    generated host.
    """
    names = set(re.findall(r"^\s*(?:float|vec3|vec2|mat3|void|int)\s+(\w+)\s*\(", shared, re.M))
    text = open(path).read()
    missing = sorted(n for n in names if not re.search(r"\b%s\s*\(" % re.escape(n), text))
    if missing:
        return "FAILED: shared functions missing from this host: %s" % ", ".join(missing)
    return "OK"


def build(base, source, check_only):
    physics, shared, variables = nb.read_source(source)

    drift = check_knob_drift(source, variables)
    if drift:
        print("\nsource: %s" % base)
        print("    FAILED: scene does not declare every layer knob:")
        for d in drift:
            print("        missing %s" % d)
        return 1
    outputs = [
        ("%s.glsl"     % base, emit_shadered(physics, shared, variables), "frag"),
        ("%s.sprj"     % base, nb.emit_sprj(variables, base),             None),
        ("%s.vert"     % base, nb.VERT,                                   "vert"),
        ("%s.gdshader" % base, emit_godot(physics, shared, variables),    None),
    ]
    print("\nsource: %s" % base)
    if not check_only:
        for name, text, _ in outputs:
            with open(os.path.join(OUTDIR, name), "w") as f:
                f.write(text)
        print("wrote : %s" % ", ".join(n for n, _, _ in outputs))
    bad = 0
    for name, _, stage in outputs:
        res = nb.verify(os.path.join(OUTDIR, name), stage)
        # Only real shader hosts -- the .sprj is XML and would always "fail".
        if not res.startswith("FAILED") and name.endswith(".gdshader"):
            res = check_host_has_shared(os.path.join(OUTDIR, name), shared)
        if res.startswith("FAILED"):
            bad += 1
        print("    %-24s %s" % (name, res))
    return bad


def main():
    check_only = "--check" in sys.argv
    sources = sorted(glob.glob(os.path.join(OUTDIR, "*.frag")))
    if not sources:
        raise SystemExit("no sources found in %s" % OUTDIR)
    bad = 0
    for source in sources:
        bad += build(os.path.basename(source)[:-len(".frag")], source, check_only)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
