#version 330
out vec4 outColor;

// GENERATED by Tools/build_milkyway.py from the variant's .frag -- do not edit.
// SHADERed build. NOTE: #version must be the literal first line for SHADERed.
uniform vec2  iResolution;
uniform float iTime;
uniform vec2  iMouse;

uniform mat4 uView;
uniform mat4 uProj;
uniform vec3 uCamPos;

uniform float uMwPitch;
uniform float uMwYaw;
uniform float uMwCoreAngle;
uniform float uMwWidth;
uniform float uMwTaper;
uniform float uMwNoiseScale;
uniform float uMwBright;
uniform float uMwDust;
uniform float uMwDustWidth;
uniform float uMwDustOffset;
uniform float uMwCore;
uniform float uMwCoreSize;

// ===== PHYSICS ==================================================================
// The band maths lives in milkyway.inc.glsl (below).

// ===== SHARED MATHS =============================================================
// milkyway.inc.glsl — the Milky Way as overlapping, sky-spanning components.
//
// This is NOT a distant galaxy (see Space/Galaxy for that) and NOT a volume: we are
// inside it, and it stretches across the sky. It is built from three overlapping things,
// composed front to back:
//
//   1. a dark, turbulent band IN FRONT   — dust, silhouetted against what is behind it
//   2. a bright, turbulent band BEHIND   — the unresolved starlight of the disk
//   3. a galactic core                   — glow with its own dust
//
// Both bands are thickest toward the core and taper toward the tips.
//
// The band coordinate is simply the angle away from the galactic plane: `b = dot(dir,
// pole)`. The band is `b = 0`; `l = dot(dir, coreDir)` runs along it (+1 at the core).
//
// GPL-3.0 (see LICENSE at the repository root).

#ifndef MILKYWAY_INC_GLSL
#define MILKYWAY_INC_GLSL

// lib/hash.glsl — integer-lattice hashes, shared by every shader.
//
// Canonical sources keep `#include "lib/hash.glsl"` (repo-root-relative) and run in
// glslviewer with `-I <repo root>`. The builders inline the include, so generated
// per-host outputs stay self-contained.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_HASH_GLSL
#define LIB_HASH_GLSL

float hash13(vec3 p3) {
	p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
	p3 += dot(p3, p3.yxz + 33.33);
	return fract((p3.x + p3.y) * p3.z);
}
vec3 hash33(vec3 p3) {
	return vec3(hash13(p3), hash13(p3 + 19.19), hash13(p3 + 41.77));
}


#endif  // LIB_HASH_GLSL
// lib/noise.glsl — value noise and fbm, built on lib/hash.glsl.
//
// Requires hash13() to be included first.
//
// GPL-3.0 (see LICENSE at the repository root).

// low-frequency value noise (once per pixel is plenty at these frequencies)

#ifndef LIB_NOISE_GLSL
#define LIB_NOISE_GLSL

float vnoise(vec3 p) {
	vec3 i = floor(p), f = fract(p);
	f = f * f * (3.0 - 2.0 * f);
	float n = 0.0;
	for (int z = 0; z < 2; z++)
	for (int y = 0; y < 2; y++)
	for (int x = 0; x < 2; x++) {
		vec3 o = vec3(float(x), float(y), float(z));
		n += hash13(i + o) * (mix(1.0 - f.x, f.x, o.x)
		                    * mix(1.0 - f.y, f.y, o.y)
		                    * mix(1.0 - f.z, f.z, o.z));
	}
	return n;
}
float fbm3(vec3 p) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 3; i++) { s += a * vnoise(p); t += a; p *= 2.03; a *= 0.5; }
	return s / t;
}


#endif  // LIB_NOISE_GLSL
// lib/raymarch.glsl — helpers for raymarched volumetric layers.
//
// Pure maths with no host assumptions: camera basis, ray/box intersection, phase
// functions, and a texture-free dither. Included (inlined) by Tools/build_*.glsl.
//
// GPL-3.0 (see LICENSE at the repository root).


#ifndef LIB_RAYMARCH_GLSL
#define LIB_RAYMARCH_GLSL

#ifndef PI
#define PI 3.141592653589793
#endif

// Slab-method ray/AABB intersection (DomNomNom). Returns (tNear, tFar) in ray units;
// there is no hit when tNear > tFar.
vec2 intersectAABB(vec3 ro, vec3 rd, vec3 bmin, vec3 bmax) {
	vec3 tMin = (bmin - ro) / rd;
	vec3 tMax = (bmax - ro) / rd;
	vec3 t1 = min(tMin, tMax);
	vec3 t2 = max(tMin, tMax);
	return vec2(max(max(t1.x, t1.y), t1.z), min(min(t2.x, t2.y), t2.z));
}

// Henyey-Greenstein phase function. g in (-1, 1): negative scatters back, positive
// forward. mu is the cosine between the view ray and the light direction.
float hgPhase(float g, float cosTheta) {
	return (1.0 / (4.0 * PI)) * ((1.0 - g * g) / pow(1.0 + g * g - 2.0 * g * cosTheta, 1.5));
}

// Interleaved gradient noise: a cheap per-pixel dither, used to offset the first ray
// step so the marching does not band. No blue-noise texture needed, so it works in
// every host (SHADERed, glslviewer, Godot).
float ign(vec2 fragCoord) {
	return fract(52.9829189 * fract(dot(fragCoord, vec2(0.06711056, 0.00583715))));
}

// Camera basis: columns are right, up, -forward, so a view-space ray (forward is -Z)
// maps into world space. `fwd` is the direction the camera looks.
mat3 lookAt(vec3 fwd, vec3 up) {
	vec3 zaxis = normalize(fwd);
	vec3 xaxis = normalize(cross(zaxis, up));
	vec3 yaxis = cross(xaxis, zaxis);
	return mat3(xaxis, yaxis, -zaxis);
}


#endif  // LIB_RAYMARCH_GLSL

vec3 mwPole() {
	float cp = cos(uMwPitch);
	return normalize(vec3(sin(uMwPitch) * cos(uMwYaw), cp, sin(uMwPitch) * sin(uMwYaw)));
}

float mwFbm(vec3 p, int octaves) {
	float a = 0.5, s = 0.0, t = 0.0;
	for (int i = 0; i < 6; i++) {
		if (i >= octaves) break;
		s += a * vnoise(p);
		t += a;
		p *= 2.03;
		a *= 0.5;
	}
	return s / max(t, 1e-5);
}

vec3 milkywaySky(vec3 dir, float pxPerDir, out vec3 transmittance) {
	vec3 d = normalize(dir);
	vec3 pole = mwPole();

	vec3 up = abs(pole.y) < 0.99 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
	vec3 ax = normalize(cross(pole, up));
	vec3 ay = cross(pole, ax);
	vec3 coreDir = normalize(cos(uMwCoreAngle) * ax + sin(uMwCoreAngle) * ay);

	float b = dot(d, pole);      // across the band (0 is the midplane)
	float l = dot(d, coreDir);   // along it: +1 toward the core, -1 the far tip

	// Turbulence in BAND coordinates (l, b), not sky coordinates, so the structure is
	// stretched along the band the way the real thing is.
	vec3 q = vec3(l, b, 0.0) * uMwNoiseScale;
	float n = smoothstep(0.32, 0.78, mwFbm(q + 3.0, 5));

	// Both bands are thick toward the core and taper toward the tips.
	float taper = mix(1.0 - uMwTaper, 1.0, smoothstep(-1.0, 0.4, clamp(l, -1.0, 1.0)));

	// ---- 2. the bright turbulent band ----
	float wBright = uMwWidth * taper;
	float band = exp(-(b * b) / (wBright * wBright));
	float bright = band * (0.20 + 1.60 * n);
	float grain = smoothstep(0.60, 0.95, mwFbm(q * 3.0 + 9.0, 3));
	bright += band * grain * 1.5;    // brighter star-cloud knots

	// ---- 3. the galactic core ----
	float ang = acos(clamp(dot(d, coreDir), -1.0, 1.0));
	float core = exp(-(ang * ang) / (uMwCoreSize * uMwCoreSize));
	core *= mix(0.35, 1.0, n);       // the core has dust across it

	// ---- 1. the dark turbulent band, IN FRONT ----
	float wDark = uMwDustWidth * taper;
	float dark = exp(-pow((b - uMwDustOffset) / wDark, 2.0));
	dark *= 0.35 + 1.20 * smoothstep(0.25, 0.70, mwFbm(q * 1.4 + 21.0, 4));

	vec3 dustAbs = vec3(0.70, 0.82, 1.0);
	vec3 T = exp(-dustAbs * uMwDust * dark);

	// ---- compose: emission is behind the dark band, then the sky behind it ----
	float coreness = smoothstep(0.2, 1.0, clamp(l, -1.0, 1.0));
	vec3 brightColour = mix(vec3(0.72, 0.82, 1.00), vec3(1.00, 0.93, 0.80), coreness);
	vec3 coreColour  = vec3(1.00, 0.95, 0.85);

	vec3 col = brightColour * bright * uMwBright + coreColour * core * uMwCore;
	col *= T;

	transmittance = T;
	return col;
}

#endif  // MILKYWAY_INC_GLSL

vec3 aces(vec3 x) {
	return clamp((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0, 1.0);
}

void main() {
	vec2 ndc = (gl_FragCoord.xy / iResolution.xy) * 2.0 - 1.0;
	vec3 viewRay = vec3(ndc.x / uProj[0][0], ndc.y / uProj[1][1], -1.0);
	vec3 dir = normalize(transpose(mat3(uView)) * viewRay);
	float pxPerDir = 2.0 / (uProj[1][1] * iResolution.y);

	vec3 transmittance;
	vec3 col = milkywaySky(dir, pxPerDir, transmittance);

	col = aces(col);
	outColor = vec4(pow(col, vec3(0.4545)), 1.0);
}
